### DISCUSSION TITLE
How to secure Environment Variable value from K8s Pod Spec

### DISCUSSION THREAD

**Discussion by thaiOnpoint** [airflow-helm/charts#580] [Questions & Answers] [answered]
Hi everyone, thank you for your great work to create this chart, I'm newbie on Airflow and Kubernetes

I'm currently using:

- Airflow Version **2.2.4**
- Airflow Helm chart Version **1.5**

I'm currently using **CeleryKubernetesExecutor**, and setting some environment variables via values.yaml file like this
```
...
dags:
  gitSync:
    branch: develop
    depth: 1
    enabled: true
    maxFailures: 0
    repo: git@github.com:xxxxxx/yyy.git
    rev: HEAD
    sshKeySecret: airflow-ssh-git-secret
    subPath: airflow/dags
    wait: 20
env:
  - name: "TZ"
    value: "Asia/Saigon"
  - name: "AWS_S3_SECRET"
    value: "xxxxxxxxxxxxxxxxxxxxxxx"
  - name: "AIRFLOW_CONN_DB_A"
    value: "postgresql://postgres:postgres@dbhost:5432/public"
executor: CeleryKubernetesExecutor
...
```

The problem is, my values.yaml include some SECRET variable (like AWS key, Database connection ....) that I don't want Airflow's Users to know. But when the user run the DAG, they can click on K8s pod spec and see all things.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/101542486/168247542-201c5b08-c5b3-4c99-9c63-9362bcd23078.png">

How I can hide this K8s Pod Spec page on some User (like User/Viewer)? 
Or is there anyway that I can import my secret variable/connection in safety way? 
Thank you so much.

**Comment by thesuperzapper** [comment, marked as answer]
@thaiOnpoint 

Firstly, I want to highlight that if someone can create & run an arbitrary DAG, they can make a DAG that will `print(xxx)` anything that airflow knows, so security is only really though obscurity for those users.

However, to specifically hide the content of `AIRFLOW_CONN_DB_A` from the Airflow UI, you could:

1. Use `airflow.extraEnv` to define `AIRFLOW_CONN_DB_A` from a Secret ([see docs](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/kubernetes/mount-environment-variables.md))
2. Use `airflow.connections` to define your `db_a` connection ([see docs](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/dags/airflow-connections.md))

**Reply by thaiOnpoint** [reply]
Hello @thesuperzapper, thank you for your reply.
I tried your second solutions, but look like it doesn't work. I follow your second link, and I know that using Secret Templates is better, but i can't make it run even using plain text.
In my DAG, i have a connection code like this
```
    @staticmethod
    def create_postgres_from_conn_id(conn_id: str) -> Postgres:
        from airflow.hooks.postgres_hook import PostgresHook
        postgres_hook = PostgresHook(conn_id)
        engine = postgres_hook.get_sqlalchemy_engine()
        return Postgres(engine=engine)
```
which conn_id = `db_prod` or `db_dev`

In my `values.yaml` file, I have 

```
env:
  - name: "TZ"
    value: "Asia/Saigon"
  - name: "AIRFLOW__CORE__HOSTNAME_CALLABLE"
    value: "airflow.utils.net:get_host_ip_address"
....

airflow:
  connections:
    - id: db_prod
      type: postgres
      host: db_prod.rds.amazonaws.com
      port: 5432
      login: postgres
      password: xxxxxxxxxx
      schema: public
      extra: |
        { 
          "sslmode": "allow" 
        }

    - id: db_dev
      type: postgres
      host: db_dev.rds.amazonaws.com
      port: 5432
      login: postgres
      password: xxxxxxxxxxx
      schema: public
      extra: |
        { 
          "sslmode": "allow" 
        }
```

But when I start an Airflow, I have Broken DAGs say that both `db_prod` and `db_dev` isn't defined:

```
Broken DAG: [/opt/airflow/dags/test.py] Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 68, in get_connection
conn = Connection.get_connection_from_secrets(conn_id)
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 410, in get_connection_from_secrets
raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `db_prod` isn't defined
```
Please note that this `db_prod` and `db_dev` work correctly when I set it via `env` variable in `values.yaml` file:

```
env:
    - name: "AIRFLOW_CONN_DB_PROD"
      value: "postgresql://postgres:xxxxxxx@db_prod.rds.amazonaws.com:5432/public"
```
Do I get wrong in any step? 

Thank you so much.
