### DISCUSSION TITLE
Deploy multiple workers

### DISCUSSION THREAD

**Discussion by Rattnik** [airflow-helm/charts#637] [Questions & Answers]
Hi, I want to deploy multiple workers in k8s with different queue and image parameters. How can I do it with current helm chart?
I could do it with extra Helm install and pass in .Values (scheduler: false, webserver: false....**worker: true**) but this Helm chart doesn't contain this logic in template files. And I don't want rewrite this chart to exclude problems with merge Helm charts when new version are released.
May it can be done with sub chart? How then to place parent and child charts to save dependence: some parameters such as image I want to rewrite but more parameters i want to save from chart which deploy whole cluster. Because it contains main variables and secrets such as backend and celery broker connection which I want use in worker deploy chart.
Thanks

**Comment by thesuperzapper** [comment]
@Rattnik I agree and want to add support for multiple "celery worker queues" (with different Pod templates) in an intuitive way within the chart's values. 

Especially because once we have added task-aware autoscaling (https://github.com/airflow-helm/charts/issues/339) the combination of these features would allow having special queues like "large" or "GPU" that only scale up from 0 when a task that requests them is pending.

The main issue to consider is how to structure the values so that it does not become overwhelming. There are two possible options that immediately spring to mind, a YAML sequence, or a YAML map, something like:

```yaml
# OPTION 1: as a YAML sequence
workerQueues:
  - queueName: queue_name_1 
    replicas: 1
    resources: {}
    tolerations: []
    ...

  - queueName: queue_name_2
    replicas: 1
    resources: {}
    tolerations: []
    ...

# OPTION 2: as a YAML map
# (has the benefit of ensuing only one template for each name, but limits possible queue names to valid YAML keys)
workerQueues:
  queue_name_1: 
    replicas: 1
    resources: {}
    tolerations: []
    ...

  queue_name_2: 
    replicas: 1
    resources: {}
    tolerations: []
    ...
```
