### DISCUSSION TITLE
Airflow URL returning 404 when using Prefix

### DISCUSSION THREAD

**Discussion by tanmaykansara** [airflow-helm/charts#681] [Questions & Answers]
Hello All

Here is my set up: I have EKS where I have deployed Airflow using Helm chart. The pods are running on Fargate. I have ALB installed using helm as well. 
When I set up the config using 
```
web:
    path: "/"
    host: "k8s-dev-***************************.us-west-2.elb.amazonaws.com"
```

The UI shows up when accessing the Ingress URL. The issue comes when I am setting up a prefix:

```
ingress:
  enabled: true
  
  
  apiVersion: networking.k8s.io/v1
  
  
  web:
    path: "/airflow-dev"
    host: "k8s-dev-*********************.us-west-2.elb.amazonaws.com"
```

In the Airflow values as well, I am passing the following overrides to the pods:

```
extraEnv: |
  - name: "AIRFLOW_VAR_FOO"
    value: "Develp_foo"
  - name: "AIRFLOW__WEBSERVER__BASE_URL"
    value: "http://localhost:8080/"
```
Here is part of the Ingress yaml file:

````
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /airflow-dev/
          pathType: Prefix
          backend:
            service:
              name: airflow-dev-nodeport
              port:
                number: 8080`
```
If I change the Base_Url value to locahost:8080/airflow-dev/ the webserver Pod keeps restarting. Any idea why I am getting the 404 page when accessing the Ingress URL ?
Here is the error that I get:

![image](https://user-images.githubusercontent.com/119540699/207365625-cf649958-4c45-4512-bb5a-6d5921af94c0.png)

Ideally I want to access the Airflow using the ingress_url/airflow-dev/ . 

Thanks
