### DISCUSSION TITLE
S3 Remote Logging not working for KubernetesExecutor on AWS EKS

### DISCUSSION THREAD

**Discussion by seblum** [airflow-helm/charts#759] [Questions & Answers]
I am encountering an issue with remote logging to S3. I am running Airflow on an EKS cluster with KubernetesExecutor and KubernetesPodOperator. I digged through the documentation already but nothing worked so far.

The KubernetesOperator in my DAG looks like this:

```python
    @task.kubernetes(
        image=<IMAGE>,
        name="preprocessing",
        namespace="airflow",
        in_cluster=True,
        get_logs=True,
        do_xcom_push=True,
        service_account_name="airflow-sa",
    )
    def preprocessing_op(mlflow_experiment_id):
    ...
```

When I run my DAG I get the following logs on the UI:

<img width="1055" alt="Bildschirmfoto 2023-07-07 um 00 21 28" src="https://github.com/airflow-helm/charts/assets/64776588/755ce522-806a-4215-a40b-db6c46ab3866">

As soon as I let it fail ( in hope it stores the logs on S3 ), I get the following: 

<img width="1049" alt="Bildschirmfoto 2023-07-07 um 00 20 28" src="https://github.com/airflow-helm/charts/assets/64776588/9502af96-54d9-4a58-b14a-df1f9c4f0b71">

I am using the [community helm chart](https://github.com/airflow-helm/charts/blob/airflow-8.7.1/charts/airflow/values.yaml) version 8.7.1. as base. The following shows my settings.

```yaml

airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
    - username: user
      password: user123
      role:
        - User
        - Viewer
      email: user@example.com
      firstName: user
      lastName: user
  usersUpdate: true
  legacyCommands: false
  image:
    repository: <my-own>
    tag: 2.6.2-python3.11
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 0
  executor: KubernetesExecutor
  fernetKey: "<xyz>"

  config:
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__LOGGING__LOGGING_LEVEL: "DEBUG" 
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://airflow-log-storage/"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "AWSS3_Log_Storage"

  connections:
    - id: AWSS3_Log_Storage
      type: aws
      description: AWS connection to store logs on S3
      extra: |
        {
          "region_name": "eu-central-1"
        }
serviceAccount:
  create: true
  name: "airflow-sa"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<123456>:role/airflow-s3-access-role"
workers:
  enabled: false
flower:
  enabled: false
postgresql:
  enabled: false
redis:
  enabled: false
externalDatabase:
  type: postgres
  host: ""
  port: ""
  database: airflow_db
  user: airflow_admin
  passwordSecret: ""
  passwordSecretKey: ""
  properties: ""
dags:
  gitSync:
    enabled: true
    repo: ""
    branch: ""
    revision: HEAD
    repoSubPath: "dags"
    httpSecret: ""
    httpSecretUsernameKey: username 
    httpSecretPasswordKey: password

```

The access via the connection "AWSS3_Log_Storage" and the serviceAccount works fine when I test the connection in the UI. My guess is that I also have access to the s3 bucket via the webserver, but no logs are written. I assume my pod does not have the rights or connection to be able to write, or doesn't get any information whatsoever to log remotely.

I am still completely stuck at this point and would appreciate any help.

EDIT: I was testing it with the normal @task operator so I assume it nothing related to the kubernetesPodOperator per se..
