### DISCUSSION TITLE
Celery Broker validation fails if broker url is not passed

### DISCUSSION THREAD

**Discussion by didopimentel** [airflow-helm/charts#789] [Questions & Answers]
Hello. I don't know if this is a bug or just a misuderstanding on my side, but here it goes.

I am trying to setup Airflow in my kubernetes cluster using using the official chart. This setup uses Elasticache (Redis) as the celery backend. I use Vault as the secrets provider, and I need to pass the secret via env var. By reading the docs, I understood that if I set the following fields in values.yaml:

```yaml
enableBuiltInSecretEnvVars:
  AIRFLOW__CELERY__BROKER_URL: false

env:
  - name: AIRFLOW__CELERY__BROKER_URL
    value: vault:path/to/secret
```

Then it would automatically get the url from the environment variables. Since I want to use an external redis, I wanted to disable the one provided by the chart:

```yaml
redis:
  enabled: false
```

However, when I try to perform `helm upgrade`, the validation contained in `templates/check-values.yaml` fails, arguing that I need to set either `data.brokerUrlSecretName` or `data.brokerUrl` when I am not using the redis provided by the chart.
Am I missing something or this is a bug?

Thank you.
