### DISCUSSION TITLE
How to edit workers SecurityContext (not PodSecurityContext)

### DISCUSSION THREAD

**Discussion by luke-goddard** [airflow-helm/charts#791] [Questions & Answers]
I'm trying to add [capabilities](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container) to the workers using the kubernetes executor. This was my first attempt. 
 
```yaml
workers:
  securityContext:
    capabilities:
      add:         
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
```

On upgrade I got the following error. 

```
- workers.securityContext: Additional property capabilities is not allowed
```

After reviewing the documentation, securityContext is editing the [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podsecuritycontext-v1-core) and not the [SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#securitycontext-v1-core)

So does anyone know I would be able to edit the `SecurityContext` instead of `PodSecurityContext`? Or alternatively set the `capabilities` for the worker pods?

Thank you in advance!!

**Comment by luke-goddard** [comment]
Found the solution
```yaml
workers:
  securityContexts:
    container:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
 ```
