### DISCUSSION TITLE
How to use mounted ephemeral volume as working directory

### DISCUSSION THREAD

**Discussion by ketozhang** [airflow-helm/charts#811] [Questions & Answers]
By default, the working directory `$AIRFLOW_HOME=/opt/airflow` uses the node storage. I'd like to provision and mount a ephemeral volume (or persistent) and use that as the working directory.

Is this possible?

The values I'm thinking would look like 

```yaml
airflow:
  config:
    ...

    extraVolumeMounts:
        - name: scratch
          mountPath: /opt/airflow
          readOnly: false

    extraVolumes:
      - name: scratch
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "foobar"
              resources:
                requests:
                  storage: 10Gi
```
