### DISCUSSION TITLE
nodeSelector is not uniform across all nodes

### DISCUSSION THREAD

**Discussion by PandaWhoCodes** [airflow-helm/charts#838] [Questions & Answers]
I have used node selector in the helm
```
  executor: KubernetesExecutor

  nodeSelector:
    nodetype: app

  defaultNodeSelector:
    nodetype: app
```
but it never gives me uniform results. All my nodes arent utilized and sometimes results in job evictions
![image](https://github.com/airflow-helm/charts/assets/6967017/ee99b75e-1a0d-446c-87b1-5549e00f6e8f)

What am i doing wrong? 

The cluster is an EKS cluster
