### DISCUSSION TITLE
How to verify that backend parameters are being read on EKS?

### DISCUSSION THREAD

**Discussion by BCantos17** [airflow-helm/charts#843] [Questions & Answers]
I am following [AWS Connection option 3](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/dags/airflow-connections.md#aws-connection) here, created a role with the proper permissions and added the annotations as instructed as shown

```yaml
serviceAccount:
  annotations:
    # replace with the AWS role you have configured for IRSA
    eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXX:role/<<MY_ROLE_NAME>>"
```

but the variables are not being read. Here is the secret being outputted when I run `airflow config list`

```
[secrets]
backend = airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend
backend_kwargs = {"connections_prefix": "/airflow/connections", "variables_prefix": "/airflow/variables", "profile_name": "default"}
```
and my variables under AWS Parameter Store have the correct prefix such as `/airflow/variables/test` but nothing is being synced under airflow variables. Everything points to things being okay so I am at a lost. Does anyone know if there are any logs which indict the connection is good or if there are any errors reading into parameter store? I've be looking for a needle in a haystack and have been at this for ages. Any help would be greatly appreicated
