### DISCUSSION TITLE
logs.persistence.enabled should I do my own cleaning of logs on created PVC?

### DISCUSSION THREAD

**Discussion by XooR** [airflow-helm/charts#876] [Questions & Answers]
It's not clear to me if I use PVC with `logs.persistence.enabled` should I create my own job for cleaning this logs?
I have checked FAQ and [docs](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md#option-1---persistent-volume-claim) but I couldn't find that this is stated.
For S3/GCS it seams logical that cleanup isn't done, but that's not clear for PVC because it can be done.

Only discussion that I found [log rotation](https://github.com/airflow-helm/charts/discussions/730) which indicate that when you use PVC you need to create sidecar for cleanup.

**Comment by vsfomin** [comment]
Have you found a solution to this problem?

**Comment by XooR** [comment]
Because we use PVC for this which is shared we just made cronjob for this:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: airflow-log-cleaning
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - |
              set -o errexit &&\
              find /logs-volume -type f -mtime +7 -delete &&\
              find /logs-volume -type d -mtime +7 -empty -delete
            image: SOME_IMAGE_WITH_SHELL
            imagePullPolicy: IfNotPresent
            name: log-cleaning
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 512Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /logs-volume
              name: logs-data
          volumes:
          - name: logs-data
            persistentVolumeClaim:
              claimName: airflow-logs
  schedule: 3 1 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
```
