### DISCUSSION TITLE
Unable to override image with argocd

### DISCUSSION THREAD

**Discussion by BenjaminDecreusefond** [airflow-helm/charts#923] [Questions & Answers]
Hi ! 

We have been trying to use Airflow helm version 8.9.0 with Airflow image 2.10.2 and updated the helm in consequence
```
airflow:
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false

  image:
    repository: apache/airflow
    tag: 2.10.2-python3.9
    pullPolicy: Always

```
However, after many attemps, Airflow still loads the default version 2.8.X. We are running with argocd. We checked many times the documentation and are enable to determine why this is happening. Tried of course to delete everything many time etc etc.. but nothing change. Would you have any clue ? :) 

Regards !
