### ISSUE TITLE
PYTHONPATH environment variable not being set via airflow.extraEnv

### ISSUE THREAD

**Issue by Yinabled** [airflow-helm/charts#106]
**What is the bug?**

The `PYTHONPATH` environment variable is not being set in the Airflow environment when specified via the `airflow.extraEnv` value. Specifically, the `airflow` property values to merge with `values.yaml` are documented below.

Note that the `TESTINGVAR` variable is set properly. I confirmed by `kubectl exec`ing into `airflow-web` and printing the sourced values for both `PYTHONPATH` and `TESTINGVAR` - `TESTINGVAR` was correct whereas `PYTHONPATH` remained the default value (i.e. `/opt/python/site-packages`). 

For context, we're trying to extend our `PYTHONPATH` with the repo directory in order to import custom modules into our DAGs. (If you have any suggestions of better ways to do this as well, I'm all ears.) Any idea what might be happening here?

**What are your Helm values?**

```yaml
airflow:
  config:
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  extraEnv:
    - 
      name: PYTHONPATH
      value: "/opt/python/site-packages:/opt/airflow/dags/repo"
    -
      name: TESTINGVAR
      value: "hello123"
  extraPipPackages:
    - "apache-airflow[google]==2.0.1"
    - "SQLAlchemy==1.3.23"
```

**What is your Kubernetes Version?**:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.7800", GitCommit:"cef3156c566a1d1a4b23ee360a760f45bfbaaac1", GitTreeState:"clean", BuildDate:"2020-12-14T09:12:37Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

**Comment by thesuperzapper** [comment]
@Yinabled can you confirm if this is fixed in `8.0.2`, as PR https://github.com/airflow-helm/charts/pull/108 should have fixed it!

**Comment by Yinabled** [comment]
@thesuperzapper No, this did not resolve the issue - specifically, I'm trying to extend `PYTHONPATH` with the repo directory, i.e. `/opt/airflow/dags/repo`. It looks like #108 is trying to just set `PYTHONPATH` to `/opt/python/site-packages`, which was already happening correctly before this release.

**Comment by thesuperzapper** [comment]
So what was `PYTHONPATH` set to when you use `airflow.extraEnv` with version `8.0.2`?

Because it worked for me?

NOTE: the issue was that the chart's hard-coded `PYTHONPATH` was taking presidence over the user-provided `airfkow.extraEnv`.

**Comment by Yinabled** [comment]
This is what I did:
1. Set the merged `values.yaml` to the following:
```
airflow:
  config:
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  extraEnv:
    - 
      name: PYTHONPATH
      value: "/opt/python/site-packages:/opt/airflow/dags/repo"
  extraPipPackages:
    - "apache-airflow[google]==2.0.1"
    - "SQLAlchemy==1.3.23"
```
2. Observe that `PYTHONPATH` is still set to `/opt/python/site-packages`, and not to `/opt/python/site-packages:/opt/airflow/dags/repo` as is expected.
