### ISSUE TITLE
"Option 2b - Shared PersistentVolume" removed from readme in release 8.x

### ISSUE THREAD

**Issue by kushagra391** [airflow-helm/charts#109]
Thanks for all the work to release airflow v2.0 !

I have been using this chart with ["Option 2b" for storing persistent dags / logs](https://github.com/airflow-helm/charts/tree/0f40ffe1c1a2949463ff9c59549b4fdf75391cd1/charts/airflow#option-2b---shared-persistentvolume) on AWS EFS with `v7.16.0`

On `v8.0.1`, this continues to work fine (following the old readme)

```yaml
airflow:
  ...
  ...

  extraVolumeMounts:
    - name: synchronised-dags
      mountPath: /opt/airflow/efs
  extraVolumes:
    - name: synchronised-dags
      persistentVolumeClaim:
        claimName: efs

dags:
  path: /opt/airflow/efs/dags
  persistence:
    enabled: false

logs:
  path: /opt/airflow/efs/logs
  persistence:
    enabled: false
```

But this section seems to have been removed in the latest doc. Curious, are there plans to deprecate this eventually ?
