### ISSUE TITLE
logs persistency failed if enabled

### ISSUE THREAD

**Issue by Gmasquelier** [airflow-helm/charts#113]
**chart version 8.0.2** 

It looks like we're not able to create log persistency as the templates helpers for logs is providing mountpath and subpath parameters for volumes in the spec.

https://github.com/airflow-helm/charts/blob/8611c766992a9f7156aad450f17beb2213cf667c/charts/airflow/templates/_helpers/pods.tpl#L223

Thanks for your work on this new version otherwise.

**Comment by murilommen** [comment]
Having the same issue here! even though my Values.logs.path is not empty, it returns me this:
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "mountPath" in io.k8s.api.core.v1.Volume`

**Comment by karakanb** [comment]
I am having the same issue with the 8.0.2 release. Here's my values for reference:
```yaml
logs:
    path: /opt/airflow/logs
    persistence:
        enabled: false
        storageClass: nfs
```
