### ISSUE TITLE
allow specifying `--index` and `--index-url` in pip-install

### ISSUE THREAD

**Issue by c-thiel** [airflow-helm/charts#115]
Version 8.0.2 of the Chart

**What is your Bug?**
In 7.X.X is used to be possible to configure extraPipPackages to be installed from a non-standard registry.
This can either be done by mounting a configmap to the container or by adding env-vars.

In the 8.X.X version of the Chart this is no longer supported for the dedicated sidecar: https://github.com/airflow-helm/charts/blob/8611c766992a9f7156aad450f17beb2213cf667c/charts/airflow/templates/_helpers/pods.tpl#L77

**Workaround**
In the meantime these options can be specified in the `extraPipPackages` in the values.yaml:
```yaml
      airflow:
        extraPipPackages:
          - "my_package==0.1.5"
          - --index
          - https://forge.example.com/repository/pypi-all/pypi
          - --index-url
          - https://forge.example.com/repository/pypi-all/simple/
```

**Comment by thesuperzapper** [comment]
Bumping for bot, @c-thiel is this still an issue for you?

**Comment by thesuperzapper** [comment]
@c-thiel @johngtam this feature will be available in version `8.5.0` of the chart (to be released today/tomorrow) because of PR: https://github.com/airflow-helm/charts/pull/365

__You can now set pip configs in `airflow.config`, for example:__
```yaml
airflow:
  config:
    ## pip configs can be set with environment variables
    PIP_TIMEOUT: 60
    PIP_INDEX_URL: https://<username>:<password>@example.com/packages/simple/
    PIP_TRUSTED_HOST: example.com
  
  extraPipPackages:
    - "my-internal-package==1.0.0"
```
