### ISSUE TITLE
Configmap "airflow-env" not found, tasks won't get executed 

### ISSUE THREAD

**Issue by murilommen** [airflow-helm/charts#119]
**What is the bug?**

I'm using the newest 8.0.2 version of the helm chart on my AKS cluster and connecting to an existing Azure Postgres database. Web UI runs fine. Although the Scheduler also seems to be running fine (at least from the pod logs and status), neither default dags or the ones I have uploaded via git-sync will run. They will spawn new worker pods, but they keep with waiting with a CreateContainerConfigError. I see a message on the pods stating "configmap "airflow-env" not found". I also can't see my AIRFLOW__KUBERNETES__{ENV} variables there, so airflow.config doesn't seem to be replicating to the worker pods. Any thoughts?

**What are your Helm values?**
```yaml
airflow:
  legacyCommands: false

  image:
    repository: apache/airflow
    tag: 2.0.1-python3.8
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000

  executor: KubernetesExecutor
  fernetKey: "<my_key>"

  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"

    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: 2.0.1-python3.8
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
        
    AIRFLOW__METRICS__STATSD_ON: "True"
    AIRFLOW__METRICS__STATSD_HOST: "localhost"
    AIRFLOW__METRICS__STATSD_PORT: "8125"
    AIRFLOW__METRICS__STATSD_PREFIX: "airflow"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin

  usersUpdate: true

  connections: []
  connectionsUpdate: true

  variables: []
  variablesUpdate: false 

  pools: []
  poolsUpdate: false
  
  podAnnotations:
    ad.datadoghq.com/airflow-web.check_names: '["airflow"]'
    ad.datadoghq.com/airflow-web.init_configs: '[{}]'
    ad.datadoghq.com/airflow-web.instances: '[{"url": "%%host%%", "tls_verify": "false"}]'

  extraPipPackages:
    - "apache-airflow-providers-databricks"
    - "apache-airflow[statsd]"
    - "apache-airflow-providers-microsoft-azure"
    - "azure-storage-blob"
    - "sqlalchemy < 1.4.0" # I was getting an error when migrating the db with Sqlalchemy 1.4.0

  extraConfigmapMounts: []

  extraEnv:
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-secret
          key: sql_alchemy_conn

  extraContainers: []
  extraVolumeMounts: []
  extraVolumes: []

  kubernetesPodTemplate:
    nodeSelector:
      app: airflow-scheduler # setting workers to go to the same node as the scheduler

    podAnnotations:
      ad.datadoghq.com/airflow-web.check_names: '["airflow"]'
      ad.datadoghq.com/airflow-web.init_configs: '[{}]'
      ad.datadoghq.com/airflow-web.instances: '[{"url": "%%host%%", "tls_verify": "false"}]'

    securityContext: {}
    extraPipPackages: []
    extraVolumeMounts: []
    extraVolumes: []


scheduler:
  nodeSelector:
    app: airflow-scheduler


web:
  nodeSelector:
    app: airflow-webserver


workers:
  enabled: false

flower:
  enabled: false


logs:
  path: /opt/airflow/logs

  persistence:
    enabled: false


dags:
  path: /opt/airflow/dags

  persistence:
    enabled: false

  gitSync:

    enabled: true
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      ## values: Always or IfNotPresent
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533

    resources: {}

    repo: "git@github.com:<my_git_repo>.git"
    repoSubPath: "src/dags"
    branch: main
    revision: HEAD
    depth: 1
    syncWait: 60
    syncTimeout: 120
    httpSecret: ""
    httpSecretUsernameKey: username
    httpSecretPasswordKey: password
    sshSecret: airflow-git-private-dags
    sshSecretKey: id_rsa
    sshKnownHosts: ""

ingress:
  enabled: false



serviceAccount:
  create: true
  name: ""
  annotations: {}
extraManifests: []

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: "<my_host>"
  port: 5432
  database: airflow
  user: "<my_user>@<my_host>"
  passwordSecret: "airflow-secret"
  passwordSecretKey: "db_secret"
  properties: ""

redis:
  enabled: false
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```
