### ISSUE TITLE
airflow 2.0.0 flaskappbuilder userinfogetter issue

### ISSUE THREAD

**Issue by HariAA** [airflow-helm/charts#125]
Hi,

I am trying to implement Azure AD integration and authorization. I was able to set up the azure ad integration, but I am facing an issue with the authorization step. 
As a first set step, I need to read additional info from the azure directory(group) which has the AD group for a user and i would like to use the group to decide the appropriate permission in the airflow webserver. I am trying to create a function in the webserver_config.py file to return a modified user info but I am facing an issue with the decorator. 

I get the error "TypeError: oauth_user_info_getter() missing 1 required positional argument: 'f'"

The below code is what I have put for the user info getter.  

    from flask_appbuilder import BaseSecurityManager as smm
    @smm.oauth_user_info_getter
    def get_oauth_user_info(sm, provider, response=None):
        if provider == "azure":
            log.debug("Azure response received : {0}".format(resp))
            id_token = resp["id_token"]
            log.debug(str(id_token))
            me = self._azure_jwt_token_parse(id_token)
            #self.appbuilder.sm.oauth_remotes[provider].get("userinfo") 
            log.debug("Parse JWT token : {0}".format(me))
            return {
                "name": me["name"],
                "email": me["upn"],
                "first_name": me["given_name"],
                "last_name": me["family_name"],
                "id": me["oid"],
                "username": me["oid"],
                "role_keys": me["group"]
            }
        else:
            return {}

could someone please help me if you have used azure integration

**Comment by thesuperzapper** [comment]
@HariAA This is definitely an issue to ask on Flask-Appbuilder.

Regardless, did you follow the Flask-Appbuilder docs at the bottom of here:
https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth

I'll be honest those docs might need updating

**Comment by hussainsaify** [comment]
@HariAA Not an ideal way but you can override security manager by mounting it as a configmap for enabling authentication and authorization for azure ad in webserver values section

```
      extraVolumeMounts:
        - name: custom-security-config
          mountPath: /opt/python/site-packages/flask_appbuilder/security/manager.py
          subPath: "manager.py"
        - name: sqla-manager-config
          mountPath: /opt/python/site-packages/flask_appbuilder/security/sqla/manager.py
          subPath: "manager.py"
      extraVolumes:
        - name: custom-security-config
          configMap:
            name: my-custom-security-config
        - name: sqla-manager-config
          configMap:
            name: sqla-manager-config
```
