### ISSUE TITLE
Airflow containers don't initialize (airflow-upgrade-db)

### ISSUE THREAD

**Issue by TAMQuiroz** [airflow-helm/charts#127]
**What is the bug?**

Hello, I might be missing something but I'm using Terraform to do a fresh Airflow 2.0.1 install using the chart version 8.0.2 on an AKS Cluster and it fails because none of the containers initialize, including the container for airflow-upgrade (Not sure if this is expected as I'm trying to do a fresh installation). I'm using an external postgres db but also tried using the postgres image with the same result.

![image](https://user-images.githubusercontent.com/10441155/113634512-7e845680-9634-11eb-8dfa-8597d274e3d5.png)

Events on airflow-upgrade-db pod:

![airflow-upgrade-pod](https://user-images.githubusercontent.com/10441155/113632688-3ca5e100-9631-11eb-8de7-ad98f7685c1c.png)

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`

```
airflow:
  legacyCommands: false
  image:
    repository: apache/airflow
    tag: 2.0.1-python3.8
   extraPipPackages:
    - "azure-storage-file-datalake==12.2.2"
    - "azure-storage-blob==12.7.1"
    - "azure-servicebus==7.0.0"
    - "azure-identity==1.5.0"
    - "apache-airflow[sentry]"
    - "splunk_handler==2.2.0"
    - "python-json-logger==2.0.1"
    - "logging-config==1.0.4"
    - "pyodbc==4.0.30"
    - "pandas==1.2.2"
    - "joblib==0.16.0"
    - "scikit-learn==0.23.1"
    - "ssh2-python==0.25.0"
    - "hvac==0.10.6"
    - "numpy==1.19.5"
    - "psycopg2==2.8.6"
    - "jsonpickle==2.0.0"
    - "openpyxl==3.0.6"

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: ${var.airflow_config.db_host}
  port: 5432
  database: airflow
  user: ${var.airflow_config.db_user}
  passwordSecret: "${var.airflow_config.db_password_secret}"
  passwordSecretKey: "postgresql-password"
```
**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"41d24ec9c736cf0bdb0de3549d30c676e98eebaf", GitTreeState:"clean", BuildDate:"2021-01-18T09:12:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Any suggestion will be appreciated,
