### ISSUE TITLE
Mount file as a secret to Airflow home or to any other directories

### ISSUE THREAD

**Issue by KIRY4** [airflow-helm/charts#13]
**Is your feature request related to a problem? Please describe.**
I'm using Airflow with LDAP+RBAC. Currently I'm mounting my webserver_config.py using extraConfigmapMounts functionality from chart. Here is how it looks like: 
```
  extraConfigmapMounts:
    - name: airflow-webserver-config
      mountPath: /opt/airflow/webserver_config.py
      configMap: airflow-webserver-config
      readOnly: true
      subPath: webserver_config.py
```
Of course it is not secure because in webserver_config.py I have AUTH_LDAP_BIND_USER  and AUTH_LDAP_BIND_PASSWORD.

**Describe the solution you'd like**
I want to have ability to mount this file from secret. For example I will create secret from file and want to mount it instead of ConfigMap as I mentioned above: 
`kubectl create secret generic airflow-webserver-config --from-file=webserver_config.py -n airflow`

I know that chart have following functionality:
```
  secretsDir: /opt/airflow
  
  secrets:
    - airflow-webserver-config
```
But instead of overwriting webserver_config.py (existing/default) file in AIRFLOW_HOME (/opt/airflow) it will create directory /opt/airflow/airflow-webserver-config and put my webserver_config.py into it.

**Additional context**
I know that k8s secrets not really secrets and it is easy to decode it. But in any case it is better to keep password encoded at least with base64 than keep it as plain text...
