### ISSUE TITLE
log persistent

### ISSUE THREAD

**Issue by anyili** [airflow-helm/charts#134]
try to persistent logs using volume, here is what I have in the values.yaml

```yaml
logs:
  persistence:
    enabled: true
    storageClass: "-"
    accessMode: ReadWriteMany
    size: 10Gi
```

what I got from apply `heml upgrade`
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "mountPath" in io.k8s.api.core.v1.Volume
```
it seems mountPath is not in the right indentation?
