### ISSUE TITLE
Scheduler goes off for long times

### ISSUE THREAD

**Issue by ilhnctn** [airflow-helm/charts#138]
**What is the bug?**

Airflow scheduler is offline most of the time, since the pod itself is running, health check doesn't fail but Scheduler it self is offline with a flash message as below

```text
The scheduler does not appear to be running. Last heartbeat was received { 5 - or- 50 minutes - or 2 haurs} ago.

The DAGs list may not update, and new tasks will not be scheduled.
```

**What are your Helm values?**
There aren't any custom values for scheduler itself. 

```yaml
airflow:
  executor: CeleryExecutor
  config:
    AIRFLOW__LOGGING__REMOTE_LOGGING: "False" 
    # Show config in Web UI
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

```

We are using Google's Composer and their Scheduler doesn't stay offline more then 1-2 minutes at all, so I replaced following part with Google's deployment values but it apparently didn't affect.

Google Composer Values
```yaml
...
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

Airflow Helm Chart Values
```yaml
...
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
$ helm ls
➜  git:(develop) helm ls
NAME          	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
airflow-gcp-v2	default  	26      	2021-04-09 12:58:07.458748 +0300 +03	deployed	airflow-8.0.2	2.0.1
```

**Comment by thesuperzapper** [comment]
@ilhnctn if possible, can you get the pod logs of the scheduler pod (for a case where is crashes preferably)

**Comment by ilhnctn** [comment]
Hi @thesuperzapper,
We are using a CloudSQL Postgres DB for airflow and use a [cloud_sql_proxy](https://cloud.google.com/sql/docs/postgres/sql-proxy) on a kubernetes service (proxy runs on an independent pod, not as a sidecar container) for communication between them.

Somehow sometimes proxy service randomly stops answering the requests. Maybe that is the main reason.
But in any case I would want to change `livenessProbe` in a way that guarantees either the scheduler service is running or the pod is not healthy. Currently the service is down but since the pod is running


**List Of Pods**
```sh
➜ orchestration git:(airflow_702) kubectl get pods
NAME                                            READY   STATUS    RESTARTS   AGE
airflow-backend-db-psqlproxy-554dc6847f-7nldw   1/1     Running   690        5d
airflow-gcp-v2-redis-master-0                   1/1     Running   0          5d
airflow-gcp-v2-scheduler-c7bd444d5-895zm        2/2     Running   93         28h
airflow-gcp-v2-web-6dbcd5d874-89c9k             2/2     Running   83         33h
airflow-gcp-v2-worker-0                         2/2     Running   34         28h
airflow-gcp-v2-worker-1                         2/2     Running   31         28h
```

**Logs From Scheduler**

```sh
➜ orchestration git:(airflow_702) kubectl logs airflow-gcp-v2-scheduler-c7bd444d5-895zm airflow-scheduler
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
➜  orchestration git:(airflow_702)
```

I was expecting to see more logs, but kubectl logs only show this. On GCP workload logs, I can see errors about database connection.

I will try another method for database connection and write here about the result.

**Comment by ilhnctn** [comment]
I changed database with the default stateful set one in the chart. It seems to work better then before but still can stay offline up to 5 minutes (monitored about three hours).

```yaml
postgresql:
  enabled: true
  postgresqlDatabase: airflowdb
  postgresqlUsername: airflow_user
  postgresqlPassword: some-rand-pass
```
