### ISSUE TITLE
Sidecar pattern for gce-proxy when connecting to Cloud SQL instance 

### ISSUE THREAD

**Issue by MishaVeldhoen** [airflow-helm/charts#15]
**What is your feature request?**
When deploying airflow on GKE, it would be nice to support connecting to a Cloud SQL instance through the sidecar pattern (as recommended in the [docs](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)), in a way similar to how git sync is supported currently.

**What alternatives have you considered?**
- Deploying postgres on kubernetes with a persistent storage.
- Running the proxy as a service in the airflow namespace.

**Comment by thesuperzapper** [comment]
@MishaVeldhoen I have a feeling it might already be possible with the `airflow.extraContainers` value (with the possible exception of flower, as that `airflow.extraContainers` doesn't apply to flower)

But I am not sure it will give you any more security, as the existing method of using a user/password with `externalDatabase.user` and `externalDatabase.passwordSecret`.

**Comment by MishaVeldhoen** [comment]
@thesuperzapper, yes, you are right, I had missed that option.

And about your point of more security, using the proxy I still need a user/password, but I don't have to whitelist any IP addresses or anything. And it seems to be the recommended way as per the docs linked in the issue, but I'm no expert on the topic.

**Comment by thesuperzapper** [comment]
@MishaVeldhoen if you get it working with `airflow.extraContainers`, please report back your configs.

**Comment by mdcsaenz** [comment]
@MishaVeldhoen Did you get this to work?

**Comment by MishaVeldhoen** [comment]
Hi, sorry for the late response, I did indeed get this to work using the suggestion of @thesuperzapper. Here's the relevant part of the configuration:

```yaml
airflow:

  ## sidecar containers for web/scheduler/worker
  ##
  extraContainers:
  - name: cloud-sql-proxy
    ports:
    - containerPort: 5432
    env:
    - name: DB_INSTANCE
      valueFrom:
        secretKeyRef:
          key: cloud-sql-instance
          name: mz-database-connection
    image: gcr.io/cloudsql-docker/gce-proxy:1.18.0
    command: ["/cloud_sql_proxy"]
    args: ["-instances", "$(DB_INSTANCE)=tcp:5432", "-credential_file", "/secrets/service_account.json"]
    securityContext:
      # The default Cloud SQL proxy image runs as the
      # "nonroot" user and group (uid: 65532) by default.
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /secrets/
      name: gcp-airflow-service-account-volume
      readOnly: true

  extraVolumes:
    - name: gcp-airflow-service-account-volume
      secret:
        secretName: gcp-airflow-service-account
```
