### ISSUE TITLE
Chart is not working anymore since airflow released version 2.0.2

### ISSUE THREAD

**Issue by griseau** [airflow-helm/charts#165]
**What is the bug?**

Even if in the values.yaml file I have `tag: 2.0.1-python3.8`, airflow 2.0.2 is getting deployed on one of the pod. When deploying the scheduler is not running. If I try to access the UI, I have the following : 
![image](https://user-images.githubusercontent.com/48803465/115362645-084e2b00-a1c2-11eb-8a9e-4e8a0ce6b160.png)

Somehow, airflow 2.0.2 is getting installed somewhere causing issue with database upgrade.

**What are your Helm values?**
```yaml
airflow.image:
    repository: apache/airflow
    tag: 2.0.1-python3.8
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000
```

**What is your Kubernetes Version?**:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.16rc1"}
```
