### ISSUE TITLE
allow users to run airflow as root

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#171]
Currently, if a user sets `airflow.image.uid` and `airflow.image.gid` to `0`, in an attempt to run airflow as root, they are met with an error `ModuleNotFoundError: No module named 'airflow'`.

It seems that airflow is installed into `/home/airflow/.local/lib/python3.8/site-packages/airflow` in the offical `apache/airflow` container images, and obviously the local python install directory for the `airflow` user is not present in the `PYTHONPATH` for the root user.

This is primarily caused by how we overwrite the [ENTRYPOINT](https://github.com/apache/airflow/blob/2.0.2/Dockerfile#L535) to [remove the `/entrypoint` usage](https://github.com/airflow-helm/charts/blob/airflow-8.0.8/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L103-L105), which removes the smarts of the [entrypoint.sh](https://github.com/apache/airflow/blob/2.0.2/scripts/in_container/prod/entrypoint_prod.sh) from airflow.

We could address this a few ways, but we want to make sure that we still support the `1.10.X` docker images, as the entrypoint has changed over time, for example, here is the one [for 1.10.12](https://github.com/apache/airflow/blob/1.10.12/scripts/prod/entrypoint_prod.sh)

**Comment by thesuperzapper** [comment]
For now, you can set these values as a fix:
```yaml
airflow:
  image:
    uid: 0
    gid: 0

  extraEnv:
    - name: PYTHONPATH
      value: "/opt/python/site-packages:/home/airflow/.local/lib/python3.8/site-packages/"

```
