### ISSUE TITLE
Why do external db/redis passwords need to be passed in as pre-existing secrets?

### ISSUE THREAD

**Issue by juandiegopalomino** [airflow-helm/charts#193]
Why not just pass it in directly with the other external configs, e.g.:
```yaml
externalDatabase:
  type: postgres
  host: postgres.example.org
  port: 5432
  database: airflow_cluster1
  user: airflow_cluster1
  password: blah
```
