### ISSUE TITLE
DAG storage in shared volume in access mode ReadOnlyMany not working on GKE

### ISSUE THREAD

**Issue by jherrmannNetfonds** [airflow-helm/charts#196]
**What is the bug?**
If I want to store the dags an a pre populated PersistentVolume in Google Kubernetes Engine in ReadOnlyMany mode, following [this ](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/readonlymany-disks) tutorial from google. The installation is stuck in the init phase since either scheduler or webserver pod will bind the PVC in ReadWriteOnce and the remaining pod will get Resource already in use when it tries to bind the PersistentVolume.
Root cause: `readOnly: true` is missing for VolumeMounts and Volumes with the name dags-data. Probably related to [this issue](https://github.com/kubernetes/kubernetes/issues/70505) and might be solved by [this pull request](https://github.com/kubernetes-csi/external-provisioner/pull/469).

**What are your Helm values?**
Important part is in dags:
```yaml
dags:
  ## the airflow dags folder
  ##
  path: /opt/airflow/dags

  ## configs for the dags PVC
  ##
  persistence:
    ## if a persistent volume is mounted at `dags.path`
    ##
    enabled: false

    ## the name of an existing PVC to use
    ##
    existingClaim: airflowdags-pvc
```

PV & PVC 
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowdags-pv
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: dev
    name: airflowdags-pvc
  gcePersistentDisk:
    pdName: # previously created disk name
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowdags-pvc
  namespace: dev
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
``` 

**What is your Kubernetes Version?**:
v1.18.16-gke.2100

**What is your Helm version?**:
v3.5.3

**chart version?**:
v8.0.9

**(dirty) Workaround:**
Disable `dags.persistence.enabled` and add this to `values.yaml`
```yaml
airflow:
  extraVolumeMounts:
    - name: dags-data
      mountPath: /opt/airflow/dags
      readOnly: true

  extraVolumes:
    - name: dags-data
      persistentVolumeClaim:
        claimName: airflowdags-pvc
        readOnly: true
```

**Possible Solution**
The chart should add the readOnly flag if ROX is set. I can create a pull request if this is a general solution for all k8 environments.
