### ISSUE TITLE
8.1.0 deleting dags pvc created with 7.15.0

### ISSUE THREAD

**Issue by enriqueayala** [airflow-helm/charts#208]
**What is the bug?**

I'm currently testing migration from chart version 7.15.0 to 8.1.0 and trying to maintain dags pvc created with 7.15.0 . However , when upgrading to 8.1.0 , a new pvc  is created . 

I have tested `dags.persistence.existingClaim` but dags pvc is also deleted cause it not longer exist on rendered yaml files (haven't found any workaround with `helm upgrade` to prevent it ) . 

Would it be possible to add a new variable on [pvc-dags.yaml](../blob/airflow-8.1.0/charts/airflow/templates/pvc-dags.yaml#L1) to prevent this  ? or remove "%s-dags" ? 

Any other workaround to suggest? Thanks.

**What are your Helm values?**
On 7.15.0
```` 
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    storageClass: sc-ontap-nas-eco
    size: 1Gi
    accessModes:
      - ReadWriteMany
```` 
On 8.1.0
```` 
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    storageClass: sc-ontap-nas-eco
    existingClaim: airflow 
    size: 1Gi
```` 

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by thesuperzapper** [comment]
@enriqueayala read the `Known Issues` section of the `8.0.0` upgrade guide: 
https://github.com/airflow-helm/charts/blob/main/charts/airflow/UPGRADE.md#v715x--v800

**Comment by enriqueayala** [comment]
Thanks @thesuperzapper  , I've tested it but dags pvc is marked as "Terminating" after `helm upgrade` :
```console
$ kubectl get pvc
NAME                        STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
airflow                     Terminating   pvc-c5d9b1aa-93af-410b-b521-ba5fcc45209c   5Gi        ROX            sc-ontap-nas-eco   2m34s
airflow-logs                Bound         pvc-58af5a67-7c00-47d5-9b32-d09ddbb196ee   10Gi       RWX            sc-ontap-nas-eco   2m34s
```

**Comment by enriqueayala** [comment]
As a workaround I've applied the following : 
1. Download of helm chart 7.15.0
```console
helm fetch airflow-stable/airflow --version 7.15.0
```
2. Modification of local airflow/templates/pvc.yaml to set `"helm.sh/resource-policy": keep` . This is to to _skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade or helm rollback) would result in its deletion._ 
```
{{- if and (.Values.dags.persistence.enabled) (not .Values.dags.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "airflow.fullname" . }}
  ###https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ include "airflow.labels.app" . }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.dags.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dags.persistence.size | quote }}
  {{- if .Values.dags.persistence.storageClass }}
  {{- if (eq "-" .Values.dags.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.dags.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
```
3. Applied helm upgrade using customized 7.15.0 local chart to set annotation:  
```console
helm upgrade  --install airflow airflow-charts/airflow-7.15.0/airflow -f airflow_values.yaml --history-max 3
```
4. Executed helm upgrade for 8.1.0 :
````
#airflow_values_810.yaml 
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    existingClaim: airflow
  gitSync:
    enabled: false
```
```console
helm upgrade  --install airflow airflow airflow-stable/airflow -f airflow_values_810.yaml --history-max 3 --version 8.1.0
```
5. After it pvc is retained (no longer controlled by helm )..
