### ISSUE TITLE
Pods are stuck in CrashLoopBackOff, need ability to auto-recover pods

### ISSUE THREAD

**Issue by miky-schreiber** [airflow-helm/charts#215]
**What is the bug?**

Once in a few weeks the scheduler, web and worker pods are stuck in the CrashLoopBackOff status.
Looking in the logs shows nothing.
Deleting the pods solves the issue since k8s creates them again.
Is there a way to automatically delete the pods when they are stuck on CrashLoopBackOff or solve it in any other way?

**What are your Helm values?**

```
airflow:
  config:
    PYTHONPATH: "/usr/local/airflow/bi/airflow/dags:/usr/local/airflow/bi/Common:/usr/local/airflow/bi/Discrepancies:/usr/local/airflow/bi/Tableau"        
    AWS_DEFAULT_REGION: "us-west-2"    
    AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME: "86400"
    AIRFLOW__CELERY__BROKER__TRANSPORT__OPTIONS_VISIBILITY_TIMEOUT: "1200"
    AIRFLOW__WEBSERVER__LOG_FETCH_TIMEOUT_SEC: "15"
    # AIRFLOW__SCHEDULER__RUN_DURATION:"86400"
    AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC: "1"
    AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "1"
    AIRFLOW__SCHEDULER__MAX_THREADS: "4"
  extraVolumes:
    - name: data-science-git
      emptyDir: {}
    - name: git-clone-secret-ds
      secret:
        secretName: "git-sync-ds-ssh-secret"
        defaultMode: 0700
    - name: bi-east-ec2-key-pem
      configMap:
        name: bi-east-ec2-key-pem
  extraVolumeMounts:
    - name: data-science-git
      mountPath: /usr/local/airflow/data-science
    - name: bi-east-ec2-key-pem      
      mountPath: /usr/local/airflow/bi-east-ec2-key.pem
      subPath: bi-east-ec2-key.pem
      readOnly: false
  extraContainers:
    - name: git-sync-ds
      image: alpine/git:latest
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: "airflow-env"      
      command: ['sh', '-c', 'echo DS Git clone starting && /home/airflow/git/git-clone.sh git@github.com:next-insurance/data-science.git master /dags github.com 22 gitSshKey && /home/airflow/git/git-sync.sh git@github.com:data-science/bi.git master /dags github.com 22 gitSshKey 600']
      volumeMounts:    
        - name: data-science-git
          mountPath: "/dags"
        - name: git-clone
          mountPath: /home/airflow/git
        - name: git-clone-secret-ds
          mountPath: /keys
      resources:
        requests:
          cpu: "10m"
          memory: "200M"

    volumeMounts:    
        - name: dags-data
          mountPath: /dags
      resources:
        requests:
          cpu: "10m"
          memory: "200M"
dags:
  path: /usr/local/airflow/bi
  git:
    url: "git@github.com:next-insurance/bi.git"
    ref: master
    secret: "git-sync-ssh-secret"
    sshKeyscan: true
    privateKeyName: gitSshKey
    repoHost: "github.com"
    repoPort: 22
    gitSync:
      enabled: true
      image:
        repository: alpine/git
        ## values: Always or IfNotPresent
        pullPolicy: IfNotPresent
      refreshTime: 60
      resources:
        requests:
          cpu: "10m"
          memory: "200M"
  initContainer:
    enabled: true
    image:
      repository: alpine/git
    ## values: Always or IfNotPresent
      pullPolicy: IfNotPresent
scheduler:
  variables: |
    { 
 ...
   }
  securityContext: # for S3 logging
    fsGroup: 65534
 web:
  replicas: 2
  service:
    annotations: {service.beta.kubernetes.io/aws-load-balancer-internal: "true"}
    sessionAffinity: "None"
    sessionAffinityConfig: {}
    type: LoadBalancer
    externalPort: 8080

   loadBalancerSourceRanges: []
    nodePort:
      http: ""
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 120
    timeoutSeconds: 60
    successThreshold: 1
    failureThreshold: 3
  securityContext: # for S3 logging
    fsGroup: 65534
workers:
  resources:
    requests:
      memory: "6Gi"
  replicas: 4
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  autoscaling:
    enabled: true
    maxReplicas: 16
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  celery:
    instances: 16
    gracefullTermination: true
    gracefullTerminationPeriod: 1500 
  terminationPeriod: 300
  securityContext: # for S3 logging
    fsGroup: 65534
flower:
  service:
    annotations: {service.beta.kubernetes.io/aws-load-balancer-internal: "true"}
    sessionAffinity: "None"
    sessionAffinityConfig: {}
    type: LoadBalancer
    externalPort: 5555
    #loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort:
      http: ""

###################################
# Airflow - Logs Configs tp PV
###################################
logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    existingClaim: "efs-claim"
    storageClass: "efs-sc"
    accessMode: ReadWriteMany 
    size: 50Gi
    
```

**What is your Kubernetes Version?**:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
