### ISSUE TITLE
cannot use serviceMonitor options

### ISSUE THREAD

**Issue by sawaca96** [airflow-helm/charts#218]
**What is the bug?**

now I try to make monitoring system 

so change option `serviceMonitor.enabled : true` then helm install 
but below error occured
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

**What are your Helm values?**

```
airflow:
  image:
    repository: apache/airflow
    tag: 2.0.2-python3.8
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000

  executor: KubernetesExecutor

  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Seoul
    PYTHONPATH: $PYTHONPATH:/opt/airflow/dags/repo
  
  connections: 
    - id: msteams_webhook_url
      type: http
      host: # Fill in using the dashboard.
      schema: https

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin

  extraPipPackages: 
    - airflow-exporter

web:
  webserverConfig:
    stringOverride: |-
      """Default configuration for the Airflow webserver"""
      import os
      from flask_appbuilder.security.manager import AUTH_DB
      from airflow.configuration import conf
      basedir = os.path.abspath(os.path.dirname(__file__))
      # The SQLAlchemy connection string.
      SQLALCHEMY_DATABASE_URI = conf.get('core', 'SQL_ALCHEMY_CONN')
      # Flask-WTF flag for CSRF
      WTF_CSRF_ENABLED = True
      AUTH_TYPE = AUTH_DB
      APP_THEME = "flatly.css"

workers:
  enabled: false

flower:
  enabled: false

redis:
  enabled: false

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    existingClaim: ""
    subPath: ""
    storageClass: ""
    accessMode: ReadWriteMany
    size: 1Gi

dags:
  path: /opt/airflow/dags

  gitSync:
    enabled: true

    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      ## values: Always or IfNotPresent
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533

    repo: *****
    repoSubPath: dags
    branch: *****
    revision: HEAD
    depth: 1
    syncWait: 60
    syncTimeout: 120
    httpSecret: "airflow-http-git-secret"
    httpSecretUsernameKey: username
    httpSecretPasswordKey: password

postgresql:
  enabled: true

  postgresqlDatabase: airflow
  postgresqlUsername: postgres
  postgresqlPassword: airflow

  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

serviceMonitor:
  enabled: true
  selector:
    prometheus: kube-prometheus
  path: /admin/metrics
  interval: "30s"

prometheusRule:
  enabled: false
  additionalLabels: {}
  groups: []
```

**What is your Kubernetes Version?**:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

### Additional  Question
after install `airflow-exporter`, I can see metrics from `/admin/metrics` 

but I don't know how I can export metrics to permetheus ?
