### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/helper.py'

### ISSUE THREAD

**Issue by aushafy** [airflow-helm/charts#228]
**What is the bug?**

when I refer to the docs, there is a configuration dags.path but somehow I got the following error from web server 
![image](https://user-images.githubusercontent.com/42592443/122855964-3e359a00-d340-11eb-8426-4b0e30d6cc98.png)

when I cek from /configuration url path, there is any difference between configuration from airflow.cfg that pointing to /opt/airflow/dags and from running configuration that I got the another dags path pointing to /opt/airflow/repo

**What are your Helm values?**

here is my values.yaml
```
dags:
  path: /opt/airflow
  gitSync:
    enabled: true
    repo: "ssh://git@xxx.xx.xx:xx/xx/xx/airflow.git"
    repoSubPath: "dags"
    branch: xxx
    revision: HEAD
    syncWait: 300
    sshSecret: "xxx"
    sshSecretKey: xxx
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.4900", GitCommit:"2812f9fb0003709fc44fc34166701b377020f1c9", GitTreeState:"clean", BuildDate:"2021-03-19T09:19:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

```
