### ISSUE TITLE
Unable to disable host key checking

### ISSUE THREAD

**Issue by PiePra** [airflow-helm/charts#229]
**What is the bug?**
I have a use case where our gitlab is a docker container so i have to customize known hosts to work with ssh.

Host key verification failed. Neither of adding host key to knownHosts, setting knownHosts to "" to ignore host key verification or setting env GIT_KNOWN_HOSTS to false seem to get me past host key checking

 "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b master --depth 1 git@gitlab______ /dags): exit status 128: { stdout: \"\", stderr: \"Cloning into '/dags'...\\nHost key verification failed.\\r\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\" }"  "failCount"=0

**What are your Helm values?**

```
  gitSync:
    enabled: true
    repo: git@gitlab____.git
    branch: master
    rev: HEAD
    root: "/git"
    dest: "repo"
    depth: 1
    maxFailures: 0
    subPath: "dags"
    credentialsSecret: airflow-http-git-secret
    knownHosts: gitlab____ ecdsa-sha2-nistp256 *****
    wait: 60
    containerName: git-sync
    uid: 65533
    extraVolumeMounts: []
    env:
      - name: GIT_KNOWN_HOSTS
        value:  false
```

**What is your Kubernetes Version?**:

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
