### ISSUE TITLE
Remote logging in gcs bucket dont working

### ISSUE THREAD

**Issue by rjribeiro** [airflow-helm/charts#237]
**What is the bug?**
I set the login as remote but it's not working. As credentials, I mounted a volume on all pods with a json service account. I checked the pods and json is there. With this json I created a connection with gcp, but the remote logging is not working

*** Unable to read remote log from gs://xxxxxxxx/prd/anexador_validacao_telefone/truncate_phone_validation_pos_blacklist/2021-06-24T12:47:58.679891+00:00/1.log
*** 404 GET https://storage.googleapis.com/download/storage/v1/b/xxxxxxxxx/o/prd%2Fanexador_validacao_telefone%2Ftruncate_phone_validation_pos_blacklist%2F2021-06-24T12%3A47%3A58.679891%2B00%3A00%2F1.log?alt=media: No such object:

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`
```
airflow:
  legacyCommands: false

  image:
    repository: apache/airflow
    tag: 2.0.1-python3.8
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000

  config:
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
    PYTHONPATH: $PYTHONPATH:/opt/airflow/dags:/opt/airflow/dags/repo

    AIRFLOW__CORE__LOAD_EXAMPLES: "True"

    ## remote log storage
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "gs://xxxxxxx/prd"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "GCP-ECDT-DADOS"

  connections:
    - id: GCP-ECDT-DADOS
      type: google_cloud_platform
      description: GCP-ECDT-DADOS
      extra: |-
        {"extra__google_cloud_platform__project": "xxxxxxxxx",
          "extra__google_cloud_platform__key_path": "/opt/airflow/secrets/gcs_credentials/key.json",
          "extra__google_cloud_platform__num_retries": "5",
          "extra__google_cloud_platform__scope": "https://www.googleapis.com/auth/cloud-platform"
        }

  extraVolumeMounts:
    - name: gcs-credentials
      mountPath: /opt/airflow/secrets/gcs_credentials
      readOnly: true

  extraVolumes:
    - name: gcs-credentials
      secret:
        secretName: gcs-credentials
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```
