### ISSUE TITLE
Easily support changing the image registry

### ISSUE THREAD

**Issue by vdwees** [airflow-helm/charts#26]
It would be nice if airflow.image.repository supported defining the image registry separately from the image repository. This could be done either by invoking the `tpl` command when accessing the image repository from values, or by splitting them explicitly as is done by [bitnami](https://github.com/bitnami/charts/tree/master/bitnami/airflow#parameters)

**Comment by thesuperzapper** [comment]
@vbehar Given this would be a breaking change, we are unlikely to do it unless there is a significant benefit.

Can you think of one?

**Comment by vbehar** [comment]
> @vbehar Given this would be a breaking change, we are unlikely to do it unless there is a significant benefit.

@thesuperzapper, do you mean @vdwees ? ;-)

**Comment by vdwees** [comment]
Correct me if I'm wrong, but if you prefix the access of the repository prop with the `tpl` function, it would enable injecting an alternative template without breaking the api. For example:
```diff
- image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
+ image: {{ tpl .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
```

**Comment by thesuperzapper** [comment]
@vdwees, obviously we could do numerous funky things, but my question remains, why is the needed?

**Comment by vdwees** [comment]
Sure, here is an example. If I am writing parentchart that uses this airflow chart as a sub-chart, I might write in parentchart's `values.yaml`:
```yaml
global:
  imageRegistry: internal.registry.mycompany.com
airflow:
  airflow:
    image:
      repository: internal.registry.mycompany.com/airflow
```
Now the chart works on mycompany's internal kubernetes cluster. Great! But mycompany wants to deploy the parent chart on AWS's us-east-1 data center. Now the image must come from some EKS on us-east-1:
```bash
helm install parentchart chart/ \
    --set global.imageRegistry=us-east-1.registry.mycompany.com \
    --set airflow.airflow.image.repository=us-east-1.registry.mycompany.com/airflow # handle airflow chart limitation
```
And now mycompany wants to deploy in the west too:
```bash
helm install parentchart chart/ \
    --set global.imageRegistry=us-west-1.registry.mycompany.com \
    --set airflow.airflow.image.repository=us-west-1.registry.mycompany.com/airflow # handle airflow chart limitation
```

As you can see, this airflow chart here hardcodes a property path in such a way that a parent chart cannot provide an abstraction- you have to always handle the chart's image registry as a special case. Most charts I have worked with either retrieve the image registry from the globals.imageRegistry prop or support templating the field. If the tpl function was used, as suggested above, the parent chart could do something like this, at least:

```yaml
global:
  imageRegistry: internal.registry.mycompany.com
airflow:
  airflow:
    image:
      repository: "{{ .Values.global.imageRegistry }}/airflow"
```

This way parentchart can provide proper abstraction and you only need one `--set` argument to set the image registry.
