### ISSUE TITLE
use Secrets & ConfigMaps in `airflow.{connections, pools, users, variables}` definitions 

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#260]
Currently, users are limited to defining connections/pools/users/variables in plain-text using the `airflow.{connections, pools, users, variables}` values.

There are some significant issues with our current [Job based approach](https://github.com/airflow-helm/charts/tree/airflow-8.3.2/charts/airflow/templates/jobs):
1. any sensitive content is stored in plain-text within the users `values.yaml`
2. users must re-deploy the chart to update connections 
    - that is, they aren't dynamically syncable from an external secret manager
3. if connections are manually updated in the Airflow WebUI, they are not reverted until the next `helm install` (assuming `airflow.connectionsUpdate = true`)
    - it would be better if changes were immediately reverted, so a user does not make a change, then forget about it, only to have it undone in a week or two (when they have forgotten).

One idea is to allow `extraEnv` to be passed to each job (proposed in issue https://github.com/airflow-helm/charts/issues/183). However, because of __issue 2__ above, connections will only be updated/synced on `helm upgrade`, meaning users may not realise that the connections which used Secrets __will not be updated__ if the Secret value changes.

---

I think a sensible values structure for referencing values from Secrets/ConfigMaps in `airflow.connections` is as follows:

```yaml
airflow:
  # can reference `airflow.connectionsTemplates` keys with bash-like syntax
  connections:
    - id: my_gcp
      type: google_cloud_platform
      description: my GCP connection
      login: $GCP_USERNAME
      extra: |-
        { "extra__google_cloud_platform__keyfile_dict": "${GCP_PASSWORD}" }

  # definitions of were to get Secrets/ConfigMap values
  connectionsTemplates:
    GCP_PASSWORD:
      kind: secret
      name: my-secret
      key: password
    GCP_USERNAME:
      kind: configmap
      name: my-configmap
      key: username

  # if "true" : we perpetually sync connections
  #     - updating if Secrets/ConfigMaps change
  #     - reverting changes from WebUI
  # if "false": we only create new connections
  #     - leaving any with the same `id` as they are (allows updating in WebUI)
  connectionsUpdate: true
```

To achieve this we can create a new `connections-sync` Deployment, which is simply a Python container, with the keys of `airflow.connectionsTemplates` mounted as volumes. The Python script would perpetually check for changes in the Secretes/ConfigMaps, and from the WebUI. If changes are detected, it will bring the defined connections back to their proper value.

Obviously, we can do similar for pools, users, and variables.
