### ISSUE TITLE
Configuration - can't connect with external postgres instance

### ISSUE THREAD

**Issue by TheGeniesis** [airflow-helm/charts#280]
Hi, I'm not sure if it's bug or my misunderstanding of documentation.

**Goal**
My goal is to create environment with external database (Postgres).

**Versions**
- Chart: `8.3.2`
- Airflow image: `2.0.2-python3.8`
- helm: `version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}`
- kubectl Client Version: `version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}`
Server Version: `version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Specification**
I followed documentation and finished with values-develop.yaml

```yaml
airflow:
  extraPipPackages: []
  image:
    tag: 2.0.2-python3.8
  
  executor: KubernetesExecutor

  variables:
    - key: "environment"
      value: "acceptance"

  pools: []

  fernetKey: "<fernetKey>"
  
  config:
    AIRFLOW__API__AUTH_BACKEND: "<data>"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "True"
    AIRFLOW__ELASTICSEARCH__END_OF_LOG_MARK: "end_of_log"
    AIRFLOW__ELASTICSEARCH__HOST: "<data>"
    AIRFLOW__ELASTICSEARCH__JSON_FIELDS: "asctime, filename, lineno, levelname, message"
    AIRFLOW__ELASTICSEARCH__JSON_FORMAT: "True"
    AIRFLOW__ELASTICSEARCH__LOG_ID_TEMPLATE: "{dag_id}_{task_id}_{execution_date}_{try_number}"
    AIRFLOW__ELASTICSEARCH__WRITE_STDOUT: "True"
    AIRFLOW__EMAIL__EMAIL_BACKEND: "<data>"
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__SMTP__SMTP_HOST: "<data>"
    AIRFLOW__SMTP__SMTP_STARTTLS: "<data>"
    AIRFLOW__SMTP__SMTP_SSL: "<data>"
    AIRFLOW__SMTP__SMTP_PORT: "<data>"
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "<data>"
    AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: "graph"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  
  kubernetesPodTemplate:
    extraPipPackages:
      - "toml==0.10.2"

postgresql:
  enabled: false

externalDatabase:
  host: <data>
  port: <data>
  database: <data>
  user: <data>
  passwordSecret: "<data>"
  passwordSecretKey: "<data>"
  properties: ""

scheduler:
  extraPipPackages:
    - "toml==0.10.2"
    
flower:
  enabled: false

workers:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: "<data>"
    repoSubPath: "dags"
    branch: develop
    httpSecret: "<data>"
    syncWait: 10

ingress:
  enabled: true

redis:
  enabled: false
```

And execution of helm:

```yaml
    helm3 upgrade $RELEASE_NAME \
        airflow-stable/airflow \
        --kubeconfig ./kubeconfig \
        --namespace $NAMESPACE \
        --version 8.3.2 \
        --values values.yaml \
        --set ingress.web.host=$AIRFLOW_URL \
        --set dags.gitSync.branch=$BRANCH_NAME \
        --values values-develop.yaml  \
        --install
```

**Debugging & tests**
When I check logs for scheduler pod's container `airflow-schedule` I see error:

```raw
[2021-07-07 05:28:20,249] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) could not connect to server: Connection timed out
	Is the server running on host "<host>" and accepting
	TCP/IP connections on port <port>?
```

The same thing repeats when I try to execute some DAG related action. A pod is created correctly, but fails with db connection.

The pod with a web app works correctly (when I execute nc -vz <postgres_host> <postgres_port> it can connect).

I did a quick test and copy-pasted the [webserver service](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-service.yaml), then changed names to fit with a scheduler and it fixed db connection for the scheduler.

For pods created to execute DAG related actions I couldn't create service, since there is no deployment. 

When I tried version with internal postgres (postgres.enabled=true) everything works fine.

**Question**

How to configure scheduler and DAG related pods to be able to connect with external database in proper (expected by you) way?

**Comment by wyattshapiro** [comment]
The log looks like you are submitting the literal value "<host>" as the host for the postgres db. Try replacing <host> with the actual host of the running external db. Same thing goes for user, password, port, etc

**Comment by thesuperzapper** [comment]
@TheGeniesis a few questions:
- Are you using something like istio (which can prevent outbound connections from pods)?
- Did you run `nc -vz <postgres_host> <postgres_port>` from WITHIN the scheduler container (or from your laptop)?
- Can you explain what you mean when you said:
> I did a quick test and copy-pasted the webserver service, then changed names to fit with a scheduler and it fixed db connection for the scheduler.

**Comment by TheGeniesis** [comment]
> The log looks like you are submitting the literal value `<host>` as the host for the postgres db (unless you purposefully censored that from this post). Try replacing with the actual host of the running external db. Same thing goes for user, password, port, etc. Hardcoding the values is likely fine to test locally as long as you don't commit the creds to a repo for all to see!

Hi @wyattshapiro thank you for the answer. I replaced it. In the original error message, it shows the correct IP address and correct port.
As I wrote before this configuration works correctly when I create a service for the scheduler pod.

Hi @thesuperzapper Here are answers:

> Are you using something like istio (which can prevent outbound connections from pods)?
I don't think so, but I will double-check it

> Did you run nc -vz <postgres_host> <postgres_port> from WITHIN the scheduler container (or from your laptop)?
First, I executed it from webserver pod to be sure that it works (and works), then I executed it from the scheduler pod (airflow-schedule container). 
From my laptop, I used Dbeaver to check if DB is reachable and yes, it is.

> Can you explain what you mean when you said
I created a new file, copied webserver service content, and replaced values to fit with the scheduler. Then I executed kubectl apply and repeated deployment. 
The configuration was like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: <name>-web
  labels:
    app: <name>
    component: scheduler
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app: <name>
    component: scheduler
    release: {{ .Release.Name }}
  sessionAffinity: "None"
  ports:
    - name: web
      protocol: TCP
      port: 8080
      nodePort: 30000
      targetPort: 8080
```

With service, the scheduler was able to connect external DB (I stopped receiving errors). When I removed it the problem has returned.
