### ISSUE TITLE
How to apply "pullSecret" to KubernetesExecutor in airflow 7.16.0

### ISSUE THREAD

**Issue by stephen-lazarionok** [airflow-helm/charts#292]
Version: 7.16.0

What is the way to apply "pullSecret" to KubernetesExecutor

The current config is:
```
executor: KubernetesExecutor
  config:
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "myrepo/airflow-dags"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "mytag"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
```

What I am looking for is something like `AIRFLOW__KUBERNETES__WORKER_PULL_SECRET: "secretName"`
