### ISSUE TITLE
add `airflow.defaultSecurityContext` value

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#296]
Currently, we don't set `securityContext.fsGroup` automatically for the user, this means that volumes mounted to containers will not necessarily be read/writable (due to file permissions), this can result in issues, like:
- https://github.com/helm/charts/issues/23589
- https://github.com/airflow-helm/charts/issues/109#issuecomment-877559005.

Right now, to set `fsGroup` on all Pods (for example, if [they mount PVS for logs](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-persist-airflow-logs)), they have to set `securityContext` in many places:
```yaml
airflow:
  kubernetesPodTemplate:
    securityContext:
      fsGroup: 65534
      
  sync:
    securityContext:
      fsGroup: 65534

scheduler:
  securityContext:
    fsGroup: 65534

web:
  securityContext:
    fsGroup: 65534

workers:
  securityContext:
    fsGroup: 65534

flower:
  securityContext:
    fsGroup: 65534
```

__We should add a new  value which sets `securityContext` for all Deployments/StatefulSets (with a default `fsGroup` value):__
```yaml
airflow:
  defaultSecurityContext:
    fsGroup: 0
```

__NOTES:__
- users can unset `fsGroup` if they want, by setting `airflow.defaultSecurityContext = {}`:
    - they might do this as `fsGroup` can have a startup time penalty while it recursively changes file permissions
- we should WARN users to remove their custom `xxx.securityContext.fsGroup` in CHANGELOG
     - they might have set `fsGroup` it to a different value, which would cause permissions to change back and forwards as different containers start
- if `airflow.defaultSecurityContext` AND `xxx.securityContext` are set, then `xxx.securityContext` should take presidence
- we should update [How to persist logs?](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-persist-airflow-logs) to remove the `securityContext` in example values (and replace with `defaultSecurityContext`)
- we should also update the issue for this on the original stable/airflow repo: 
  - https://github.com/helm/charts/issues/23589
