### ISSUE TITLE
add `airflow.{defaultNodeSelector,defaultAffinity,defaultTolerations}` values

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#313]
Currently if users want to set `affinity`, `tolerations` or `node-selectors` on every Pod deployed by the chart, they have to configure __a lot__ of values:

```yaml
airflow:
  kubernetesPodTemplate:
    nodeSelector: {}
    affinity: {}
    tolerations: []

  sync:
    nodeSelector: {}
    affinity: {}
    tolerations: []

scheduler:
  nodeSelector: {}
  affinity: {}
  tolerations: []

web:
  nodeSelector: {}
  affinity: {}
  tolerations: []

workers:
  nodeSelector: {}
  affinity: {}
  tolerations: []

flower:
  nodeSelector: {}
  affinity: {}
  tolerations: []

# WARNING: not sure if it is currently possible with the embedded postgres
postgresql: {}

# WARNING: not sure if it is currently possible with the embedded redis
redis: {}
```

__We should add some global variables which define `affinity`, `tolerations` or `node-selectors` for all Pods:__
```yaml
airflow:
  defaultNodeSelector: {}
  defaultAffinity: {}
  defaultTolerations: []
```

__NOTE:__
- If the user defines __both__ global and per-resource settings, we should take the per-resource config (in its entirety).
