### ISSUE TITLE
S3 logs not working when using external database

### ISSUE THREAD

**Issue by demetrioi** [airflow-helm/charts#319]
**What is the bug?**

[[A clear description of the bug]]
S3 logs not working when using external database. When I use the internal postgres database the log is saved to S3. But doesn't work when I use mySQL or Postgres external DB

I also got error when trying to execute the dag/task using CLI in the pod/container terminal

Command:
airflow tasks run example_python_operator print_the_context "2021-07-11T00:00:00+00:00"  

Error:

ERROR - Could not create an S3Hook with connection id "xyz". Please make sure that apache-airflow[aws] is installed and the S3 connection exists. Exception : "can't register atexit after shutdown"

ERROR - Could not write logs to s3://XYZ/2021-07-11T00:00:00+00:00/1.log
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/log/s3_task_handler.py", line 191, in s3_write
    self.hook.load_string(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 58, in wrapper
    connection = self.get_connection(self.aws_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 378, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 69, in wrapper
    with create_session() as session:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 29, in create_session
    session = settings.Session()
TypeError: 'NoneType' object is not callable

**What version of the chart are you using?**:

I am using version `8.4.1`

**Executor**:

KubernetesExecutor

**What is your Kubernetes Version?**:

```console
$ kubectl version
please put the output here
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68e3e47dad98b808ba41087c0c62e80cd4fcec36", GitTreeState:"clean", BuildDate:"2021-05-25T02:41:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What is your Helm version?**:

```console
$ helm version
please put the output here
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}

**Please copy your custom Helm values file:**

```yaml
postgresql:
  enabled: false

externalDatabase:
  ## the type of external database: {mysql,postgres}
  ##
  type: mysql

  ## the host of the external database
  ##
  host:

  ## the port of the external database
  ##
  port: 3306

  ## the database/scheme to use within the the external database
  ##
  database: airflow_cluster_dev

  ## the user of the external database
  ##
  user: ""

  ## the name of a pre-created secret containing the external database password
  ##
  passwordSecret: "airflow-postgres-key"

  ## the key within `externalDatabase.passwordSecret` containing the password string
  ##
  passwordSecretKey: "postgresql-password"


  image:
    repository: apache/airflow
    tag: 2.1.2-python3.9
```

**Postgres version**

Tried 10 and 11

**MySQL version**

5.7

**Comment by thesuperzapper** [comment]
@demetrioi can you show the rest of your values.yaml (for example the ones which specify `AIRFLOW__LOGGING__REMOTE_LOGGING`, etc)?

**Comment by demetrioi** [comment]
Sure @thesuperzapper 

`    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://xyz/airflow/logs/"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws"

  connections:
    - id: aws
      type: aws
      description: AWS Conn
      extra: |-
        { "aws_access_key_id": "${AWS_ACCESS_KEY_ID}",
          "aws_secret_access_key": "${AWS_ACCESS_KEY}",
          "region_name":"eu-west-1" }
`

**Comment by thesuperzapper** [comment]
@demetrioi 
__A couple of questions:__
1. Are any pods crashing, or is this error only visible in the airflow web-ui (under dag logs)?
2. Are you 100% sure that enabling/disabling `postgresql.enabled` reliably breaks/fixes s3 logs?
3. Where is this log comming from:
`ERROR - Could not create an S3Hook with connection id "xyz". Please make sure that apache-airflow[aws] is installed and the S3 connection exists. Exception : "can't register atexit after shutdown"`

**Comment by demetrioi** [comment]
Hi @thesuperzapper 

1. Are any pods crashing, or is this error only visible in the airflow web-ui (under dag logs)?

No. No pods crashing. I cannot see the error under dags logs because the log is configured to be saved on S3 and S3 is not working.

![2021-07-21_12-01-28](https://user-images.githubusercontent.com/10916434/126471272-2e76c722-8722-4efc-9ff2-faea08616e2f.png)

2 - Are you 100% sure that enabling/disabling postgresql.enabled reliably breaks/fixes s3 logs?

Yes. Just uninstalled and installed again. Just changing the postgres enable = true.

3 - Where is this log comming from:
ERROR - Could not create an S3Hook with connection id "xyz". Please make sure that apache-airflow[aws] is installed and the S3 connection exists. Exception : "can't register atexit after shutdown"

Using VS Code I'm opening a terminal on the web or scheduler pod/container.

![2021-07-21_12-04-48](https://user-images.githubusercontent.com/10916434/126471705-93817bc4-2e78-41a4-8a07-705a41e0260b.png)

**Comment by demetrioi** [comment]
Similar problem: `https://github.com/apache/airflow/issues/12969`

**Comment by demetrioi** [comment]
Also event using the internal postgres it just save to S3 when I hard code the S3 connection key and secret.

It not work when I use this new feature

```yaml
  connections:
    - id: s3_conn
      type: S3
      description: AWS Conn
      login: "${AWS_ACCESS_KEY_ID}"
      password: "${AWS_ACCESS_KEY}"
```

**Comment by thesuperzapper** [comment]
@demetrioi can you try with python 3.8 (or before), for example with:
```yaml
airflow:
  image:
    repository: apache/airflow
    tag: 2.1.2-python3.8
```
