### ISSUE TITLE
include `airflow.config` and `airflow.extraEnv` in pip-install container

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#324]
Currently, we do not mount the `airflow.config` or `airflow.extraEnv` into the [install-pip-packages](https://github.com/airflow-helm/charts/blob/airflow-8.4.1/charts/airflow/templates/_helpers/pods.tpl#L118-L138) init-container, causing issues like https://github.com/airflow-helm/charts/issues/322.

__We should add the mounts by including:__
```yaml
  envFrom:
    {{- include "airflow.envFrom" . | indent 4 }}
  env:
    {{- include "airflow.env" . | indent 4 }}
```

We should consider if we need to prevent certain environment variables from being passed which could break the `pip install --user` like [`PYTHONUSERBASE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUSERBASE). We can do this by running `unset PYTHONUSERBASE` in the container args.
