### ISSUE TITLE
Customizable service ports 

### ISSUE THREAD

**Issue by CyberHippo** [airflow-helm/charts#325]
**What is your feature request?**

I would like to be able to customize the port list in the service manifests.

As of now, there is only on port listed in the service (airflow-web service as an example) which can be overridden by the values:
```yaml
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
```
But it does not seem possible to add another port in the list.

The end goal here is the tell prometheus to scrape the service (web, scheduler, etc) on the port exposed by [prom/statsd_exporter](https://github.com/prometheus/statsd_exporter). 

```yaml
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
```

**What alternatives have you considered?**

- Scrape the pod directly, bypassing the service.

I am open to suggestion and if needed I can provide a PR for this feature.
