### ISSUE TITLE
update `home`, `description` & `sources` in Chart.yaml

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#331]
To be consistent with other locations in the repo, __we should update the `description` under Chart.yaml to__:
```yaml
description: Airflow Helm Chart (User Community) - used to deploy Apache Airflow on Kubernetes
```

__NOTE:__ this has to done on the next release, as updating `charts/airflow/Chart.yaml` will trigger the release workflow

---

__We should also update the `home` and `sources`:__
```yaml
home: https://github.com/airflow-helm/charts
sources:
  - https://github.com/airflow-helm/charts/tree/main/charts/airflow
```
