### ISSUE TITLE
allow adding extra RBAC rules to the airflow role

### ISSUE THREAD

**Issue by pindge** [airflow-helm/charts#334]
**What is your feature request?**

In our situation, we are using `KubernetesJobOperator` : https://github.com/LamaAni/KubernetesJobOperator, we got this error 
```
airflow_kubernetes_job_operator.kube_api.exceptions.KubeApiClientException: 
airflow_kubernetes_job_operator.kube_api.operations.CreateNamespaceResource, Forbidden: jobs.batch is forbidden: User 
"system:serviceaccount:processing:airflow" cannot create resource "jobs" in API group "batch" in the namespace "processing"
```

my feature request is to add to airflow role.
```
rbac:
   additionalRules: []
```

**What alternatives have you considered?**
after investigation, we set `rbac create: false` and manually created a role and rolebinding copied from the helm chart + the following additional rules to role.
```
rules:
  - apiGroups:
    - "batch"
    - "extensions"
    resources:
    - jobs
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"
    - "delete"
```

**Comment by thesuperzapper** [comment]
@pindge Usually, if a user needs to do this, they can just disable the default RBAC with `rbac.create = false`, and then making their own `Role` and `RoleBinding`.

__However, I do see the benefit of adding a value like `rbac.extraRules`:__
```yaml
rbac:
  extraRules:
    - apiGroups:
      - "batch"
      - "extensions"
      resources:
      - jobs
      verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
```

__NOTE:__ we will have to be careful to de-dupe between the default and user-provided rules (using some clever helm templating).
