### ISSUE TITLE
users.password how do we pass it from vault

### ISSUE THREAD

**Issue by gowdra01** [airflow-helm/charts#359]
I would like to know how do we pass password from Hashicorp vault

  users:
    - username: admin
      password: vault:/data#AIRFLOW_ADMIN_PW

I have set the podAnnotations: 
  podAnnotations: 
    vault.security.banzaicloud.io/vault-addr: "https://vault.com"
    vault.security.banzaicloud.io/vault-role: "data"
    vault.security.banzaicloud.io/vault-path: "kubernetes"

it's actually getting the text rather than the value from the vault.

can you please help.

**Comment by thesuperzapper** [comment]
@gowdra01 If you look at `Option 2 - use templates from Secrets/ConfigMaps` under [How to create airflow users?](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-create-airflow-users), you will see that `airflow.usersTemplates` can be used to create templates that are used in `airflow.users`. 

Right now, you would need to use something like [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets) to create a Kubernetes Secret from a secret in your vault.

---

However, I think it's a good feature suggestion to support the vault sidecar-injection method, so I raised an issue to track adding this feature to the chart: https://github.com/airflow-helm/charts/issues/363

**Comment by gowdra01** [comment]
Is this right what I did?

  users:
    - username: admin
      password: ${ADMIN_PASSWORD}
      role: Admin
      email: email@email.com
      firstName: admin
      lastName: admin

  ## bash-like templates to be used in `airflow.users`
  ##
  ## (See `airflow.connectionsTemplates` for docs)
  ##
  usersTemplates: 
    ADMIN_PASSWORD:
      kind: secret
      name: airflow-admin-secret
      key: password
      airflowVaultPassword: vault:/data/airflow/use#AIRFLOW_ADMIN_PW


and my secrets are below
`
apiVersion: v1
data:
  password: {{ .Values.airflow.usersTemplates.ADMIN_PASSWORD.airflowVaultPassword | b64enc }}
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.com"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
  name: airflow-admin-secret
type: Opaque
`

**Comment by thesuperzapper** [comment]
Firstly, please wrap your values in a markdown multiline code-block (so they display indentations correctly on Github).

Assuming that your `banzaicloud` annotations will populate your Secret, that should work

However, I really don't understand your usage of `airflowVaultPassword`, which is NOT a value of the chart, are you forking the chart or something?

**Comment by gowdra01** [comment]
ok wrapped my above comment properly ..
so I just created a variable `airflowVaultPassword` and passing the values from vault? how else can it be done ? is there better approach?

one more question how do update this real time ? like when we change the password in vault is there something like sync ?

**Comment by thesuperzapper** [comment]
@gowdra01 regarding the `airflowVaultPassword` why not just explicitly put the value of your password in your secret? Why are you storing it under `airflow.usersTemplates.ADMIN_PASSWORD`?

Regarding syncing, as long as `airflow.usersUpdate` is `true` (this is the default), the chart will create a Deployment that automatically updates the users if the Secrets change (or if the user is updated/removed by some external factor).

**Comment by gowdra01** [comment]
ok thanks.. do you have any examples of how we access vault from secret ?

**Comment by gowdra01** [comment]
@thesuperzapper 

is this right way to do it ?
```

  extraEnv:
    - name: VAULT_ADDR
      value: "https://vault.com"
    - name: AIRFLOW__LDAP__BIND_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-ldap-password
          key: value
          
          
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-ldap-password
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default 
  data:
    value: /loc/data/airflow/use/#LDAP_PW
```
