### ISSUE TITLE
support vault sidecar-injection with `airflow.usersTemplates`

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#363]
We support referencing Secrets/Configmaps with `airflow.usersTemplates`, which allows users to integrate with their [HashiCorp Vault](https://www.vaultproject.io/) using tools like [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets). 

However, the first-class method of secret injection in Vault is the [sidecar-injection method](https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar), which makes use of annotations that tell vault to sync a file into a Pods filesystem.

__We should let users reference a file in the Pods filesystem with `airflow.usersTemplates`, for example:__
```yaml
airflow:
  users:
    - username: admin
      password: ${MY_PASSWORD}
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin

  usersTemplates:
    MY_PASSWORD:
      kind: file
      path: /vault/secrets/MY_PASSWORD

  sync:
    podAnnotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "airflow"
        vault.hashicorp.com/agent-inject-secret-MY_PASSWORD: "airflow/users/admin/password"

```

__We should also:__
- explicitly document using vault in the README
- also make this change for `airflow.{connections,pools,variables}`
