### ISSUE TITLE
include `airflow.{config,extraEnv}` in git-sync container

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#376]
Currently, we do not mount the `airflow.config` or `airflow.extraEnv` into the [git-sync](https://github.com/airflow-helm/charts/blob/482cb29f93587cfd9c3c8b0b1cef31bdbf015dde/charts/airflow/templates/_helpers/pods.tpl#L145-L149) init-container, causing issues like not being able to set `HTTP_PROXY` (https://github.com/airflow-helm/charts/issues/180)

__We should add the mounts by including:__
```yaml
  envFrom:
    {{- include "airflow.envFrom" . | indent 4 }}
  env:
    {{- include "airflow.env" . | indent 4 }}
```

As the last defined `env` for a particular `name` takes precedence, it shouldn't be possible for users to break the git-sync configs by setting a `GIT_XXXX` config, as long as our values are defined AFTER the `{{- include "airflow.env" . | indent 4 }}`.
