### ISSUE TITLE
Errno 13 - Permission denied: '/opt/airflow/logs/scheduler

### ISSUE THREAD

**Issue by sakshi-bansal** [airflow-helm/charts#38]
**What is the bug?**
Getting permission denied, when enabling persistent volume for logs 

**What is your Kubernetes Version?**:
v1.17.11

**What is your Helm version?**:
Helm 3

Similar issue: https://github.com/helm/charts/issues/23589

**Comment by StephanZaat** [comment]
I have the same problem. I have created the workaround by attaching a PVC to /airflow_logs on the worker pod.
This allow the tasks to proceed. However, the first time the task runs, it only creates the log file, but then exits with a Permission denied.

**Comment by thesuperzapper** [comment]
@StephanZaat can you describe your environment (how are you running K8S?) and provide your `values.yaml`?

I really want to understand what's happening here.

**Comment by StephanZaat** [comment]
Thanks for the quick response. I'm running Airflow with the Bitnami Helm chart on Azure K8S.
This is my config for my worker:

```
   extraVolumeMounts:
    - name: logdir
      mountPath: /airflow_logs
  extraVolumes:
    - name: logdir
      persistentVolumeClaim:
        claimName: airflow-logs
  extraEnvVars:
    - name: AIRFLOW__CORE__BASE_LOG_FOLDER
      value: /airflow_logs
```
I'm using Azure File for the PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
```
