### ISSUE TITLE
Adding variables as Kubernetes secrets airflow is adding a linebreak

### ISSUE THREAD

**Issue by roquemoyano-tc** [airflow-helm/charts#409]
**What is the bug?**

When a variable is added as kubernetes secrets, airflow is adding a linebreak at the end. Once helm chart is installed if I go to admin->variables, and export them, I can see the linebreak:

ej;
    "source_username": "qaperformance@performance-db\n",
    "target_db_name": "targetperformance\n",
    "target_host": "performance-db.postgres.database.azure.com\n",

this problem not happen if I set the variables in values.yaml without using secrets.

**What version of the chart are you using?**:

I am using version 8.4.1

**What is your Kubernetes Version?**:
1.16.7
```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"2b13e288f94dd2577d4ff7261f9eb76b1d5692a1", GitTreeState:"clean", BuildDate:"2020-06-01T21:55:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

```

**What is your Helm version?**:

```console
$ helm version
3.0
```

**Please copy your custom Helm values file:**
```yaml
airflow:

  legacyCommands: false
  config:
    ## Database
    ## Security
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'


  image:
    repository: apache/airflow
    tag: 2.1.1-python3.8
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: "jfrog-regcred"
    uid: 50000
    gid: 50000


  variables:
   - key: "source_db_name"
     value: ${source_db_name}
   - key: "source_host"
     value: ${source_host}
   - key: "source_password"
     value: ${source_password}
   - key: "source_username"
     value: ${source_username}
   - key: "target_db_name"
     value: ${target_db_name}
   - key: "target_host"
     value: ${target_host}
   - key: "target_password"
     value: ${target_password}
   - key: "target_username"
     value: ${target_username}
   - key: "target_username3"
     value: ${target_username}
  
  variablesTemplates:
    source_db_name:
     kind: secret
     name: db-airflow
     key: source_db_name 
    source_host:
     kind: secret
     name: db-airflow
     key: source_host
    source_password:
     kind: secret
     name: db-airflow
     key: source_password
    source_username:
     kind: secret
     name: db-airflow
     key: source_username
    target_db_name:
     kind: secret
     name: db-airflow
     key: target_db_name
    target_host:
     kind: secret
     name: db-airflow
     key: target_host
    target_password:
     kind: secret
     name: db-airflow
     key: target_password
    target_username:
     kind: secret
     name: db-airflow
     key: target_username
  variablesUpdate: true

  users:
    - username: admin
      password: ${ADMIN_PASSWORD}
      firstName: admin
      lastName: admin
      role: Admin
      email: email@sanofi.com
    - username: architect
      password: ${ARCH_PASSWORD}
      role: Admin
      firstName: admin
      lastName: admin
      email: arch@sanofi.com
    - username: useradmin
      password: admin
      role: Admin
      email: useradmin@example.com
      firstName: admin
      lastName: admin
  
  usersTemplates:
    ADMIN_PASSWORD:
      kind: secret
      name: users-airflow
      key: admin-password
    ARCH_PASSWORD:
      kind: secret
      name: users-airflow
      key: arch-password
  usersUpdate: true
   
postgresql:
  enabled: false

scheduler:
  initdb: true
  extraInitContainers:
    - name: analytics-db-migrations
      image: ""
      command:
        - /bin/bash
        - -c
        - |
          mkdir -p /home/airflow/.local/bin \
          && echo 'export PATH="/home/airflow/.local/bin:$PATH"' \
          && echo "*** executing Alembic upgrade..." \
          && alembic upgrade head

externalDatabase:
  type: postgres
  host: performance-db.postgres.database.azure.com
  port: 5432
  database: airflowperformance
  user: airflowperformance@performance-db
  passwordSecret: "postgress-password"
  passwordSecretKey: "postgresql-password"
  properties: ""
```

**Comment by thesuperzapper** [comment]
@roquemoyano-tc I can't see a way that newlines would be introduced (especially if it's only in variables), can you provide the YAML for your `db-airflow` Secret?

I have a feeling you will be using a multiline YAML string like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-airflow
stringData:
  # "|" it will add a newline to the end
  source_username: |
    qaperformance@performance-db


  # "|-" has no newline
  source_username: |-
    qaperformance@performance-db
```

---

I also have a few unrelated questions about your values (which look strange):
1. Why are you setting `scheduler.initdb` (this is not a value since `8.0.0`)
2. Why do you need to set `scheduler.extraInitContainers`
3. I am surprised that `externalDatabase.user` is working with an `@` symbol in it (given issue https://github.com/airflow-helm/charts/issues/318 is not fixed in `8.4.1`)
