### ISSUE TITLE
plugins not getting loaded on ui / dags even though they show up in cli via `airflow plugins`

### ISSUE THREAD

**Issue by kushagra391** [airflow-helm/charts#418]
Hi, 

Thanks for creating this chart !

I have been trying to set up a custom plugin following [the doc](https://airflow.apache.org/docs/apache-airflow/stable/howto/define_extra_link.html) for adding a custom button

Our deployment is done via EFS mounts (for both dags and logs) (similar to [option - 2b](https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-2a---persistentvolumeclaim-chart-managed))

I tried adding plugins into it, but they don't show up in the UI (or get loaded for PythonOperator as expected). 

<img width="515" alt="Screen Shot 2021-09-02 at 3 36 50 PM" src="https://user-images.githubusercontent.com/8533562/131924870-0293b3e8-ff6d-4025-930a-b8207ab3b5c3.png">

- Interestingly, `airflow plugins` cli does show up in the list
- and I see `AIRFLOW__CORE__PLUGINS_FOLDER` correctly populated although `PLUGINS_FOLDER` is missing
- the code also runs fine locally with `docker-compose`

```
$ airflow plugins
name        | operator_extra_links | source                        | global_operator_extra_links
============+======================+===============================+============================
test_plugin | S3LogLink()          | $PLUGINS_FOLDER/bhp_plugin.py | GoogleLink()

$ printenv | grep PLUG
AIRFLOW__CORE__PLUGINS_FOLDER=/opt/airflow/efs/plugins
```

I followed steps from https://github.com/airflow-helm/charts/issues/252 and added `AIRFLOW__CORE__PLUGINS_FOLDER` 

```yaml
airflow:
  extraEnv:
    - name: AIRFLOW__CORE__PLUGINS_FOLDER
      value: /opt/airflow/efs/plugin
```

<details>

<summary>click to reveal full chart </summary>

```yaml
airflow:
  image:
    repository: '...'
    tag: 'latest'
    pullPolicy: Always

  service:
    annotations: { }
    externalPort: 8080

  extraEnv:
    - name: AIRFLOW__CORE__AIRFLOW_HOME
      value: /opt/airflow/efs
    - name: AIRFLOW__CORE__PLUGINS_FOLDER
      value: /opt/airflow/efs/plugins

  extraVolumeMounts:
    - name: synchronised-dags
      mountPath: /opt/airflow/efs
  extraVolumes:
    - name: synchronised-dags
      persistentVolumeClaim:
        claimName: efs

# configure DAGs deployment and update
dags:
  path: /opt/airflow/efs/dags
  persistence:
    enabled: false

# configure logs
logs:
  path: /opt/airflow/efs/logs
  persistence:
    enabled: false

flower:
  enabled: false

web:
  extraEnv:
    - name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
      value: true

# use external postgres
postgresql:
  enabled: false

externalDatabase:
  ...

```
</details>

- EKS: 1.18
- chart version: 8.3.2
- airflow: 2.1.1

Thanks !!
