### ISSUE TITLE
git oauth2 credentials in secrets usage

### ISSUE THREAD

**Issue by javamonkey79** [airflow-helm/charts#422]
How can oauth be used from secrets? 

If I do this:
```
dags:
  gitSync:
    repo: "https://oauth2:123abc@mycompanies.git.repo/foo/bar/baz.git"
    branch: dev_2.0
```

Where 123abc is my git key, it works. 

Also, in previous versions of this chart (I think 7.x versions), this works:
```
  git:
    url: https://oauth2:$(GIT_KEY)@mycompanies.git.repo/foo/bar/baz.git
    ref: master
    gitSync:
      enabled: "true"
      refreshTime: "60"

    - name: GIT_KEY
      valueFrom:
        secretKeyRef:
          name: secret-env-vars
          key: git-key
```

But, in the latest version of the chart, loading the key from secrets, to the repo no longer seems to work. I'm fine not baking it into the url, if that is the new way, but, I'm not sure how to use it. 

Do I just use these:
    httpSecret: "airflow-http-git-secret"
    httpSecretUsernameKey: username
    httpSecretPasswordKey: password

But, leave the username one empty?
