### ISSUE TITLE
allow users to set `ingressClassName`

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#427]
Currently, to specify an Ingress class we only expose the `ingress.web.annotations` and `ingress.flower.annotations` values, which can be used with the `kubernetes.io/ingress.class` annotation ([which is deprecated post k8s `1.18`](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation)).

__We should also allow users to directly set [`ingressClassName`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#ingressspec-v1-networking-k8s-io) by adding the following new values:__
```yaml
ingress:
  web:
    # default to unset
    ingressClassName: ""

  flower:
    # default to unset
    ingressClassName: ""
```

___NOTE:__ if the user does not set `ingressClassName`, the field should be omitted._
