### ISSUE TITLE
Git is syncing on a subpath called "repo"

### ISSUE THREAD

**Issue by 1eliton** [airflow-helm/charts#430]
Hi

We are migrating to the airflow 2.1.2 on Kubernetes and having some problems with git-sync (v3.2.2). The chart version we are using is 8.5.2.

The problem is the dags folder is pointing to "[AIRFLOW_HOME]/dags", same as the [docs](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dags-folder) says. If I print the env. variable "AIRFLOW_HOME", I can see exactly what I expected: "/opt/airflow".

Even apparently everything is fine, my dags goes to the link path as follow: "/opt/airflow/dags/repo" (see below)

```
airflow@airflow-worker-3:/opt/airflow/dags$ ls -la
total 20
drwxrwxrwx  4 root    root  4096 Sep 10 17:07 .
drwxrwxr-x  1 airflow root  4096 Sep  8 19:34 ..
drwxr-xr-x  9   65533 65533 4096 Sep 10 17:07 .git
lrwxrwxrwx  1   65533 65533   44 Sep 10 17:07 repo -> rev-c0b481f8c7bdbf3dcxx0aec96cbe6468707122ef
drwxr-xr-x 30   65533 65533 4096 Sep 10 17:07 rev-c0b481f8c7bdbf3dcxx0aec96cbe6468707122ef
```

Searching a litle bit more, I found on "chart.d/templates/_helpers/pods.tpl" a var name called "GIT_SYNC_DEST" where the value is set as "repo". If I clean this var then the new path points to "/opt/airflow/dags/K8sAirflowDags" where "K8sAirflowDags" is the name of my repo on azure repos.

To work correctly, the path shoud be exactly "[AIRFLOW_HOME]/dags".

I'll share here my **custom-values** where I define **dags** config.

```
dags:
  ## the airflow dags folder
  ##
  path: /opt/airflow/dags
  doNotPickle: false 
  installRequirements: false

  ## configs for the dags PVC
  ##
  persistence:
    ## if a persistent volume is mounted at `dags.path`
    ##
    enabled: false

    ## the name of an existing PVC to use
    ##
    existingClaim: ""

    ## sub-path under `dags.persistence.existingClaim` to use
    ##
    subPath: ""

    ## the name of the StorageClass used by the PVC
    ## - if set to "", then `PersistentVolumeClaim/spec.storageClassName` is omitted
    ## - if set to "-", then `PersistentVolumeClaim/spec.storageClassName` is set to ""
    ##
    storageClass: ""

    ## the access mode of the PVC
    ## - [WARNING] must be "ReadOnlyMany" or "ReadWriteMany" otherwise airflow pods will fail to start
    ##
    accessMode: ReadOnlyMany

    ## the size of PVC to request
    ##
    size: 1Gi

  ## configs for the git-sync sidecar (https://github.com/kubernetes/git-sync)
  ##
  gitSync:
    ## if the git-sync sidecar container is enabled
    ##
    enabled: true

    ## the git-sync container image
    ##
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533

    ## the url of the git repo
    ##
    ## ____ EXAMPLE _______________
    ##   # https git repo
    ##   repo: "https://github.com/USERNAME/REPOSITORY.git"
    ##
    ## ____ EXAMPLE _______________
    ##   # ssh git repo
    ##   repo: "git@github.com:USERNAME/REPOSITORY.git"
    ##
    repo: url@of@our@git@repo

    ## the sub-path within your repo where dags are located
    ## - only dags under this path within your repo will be seen by airflow,
    ##   (note, the full repo will still be cloned)
    ##
    repoSubPath: ""

    ## the git branch to check out
    ##
    branch: develop

    ## the number of seconds between syncs
    ##
    syncWait: 30

    ## the max number of seconds allowed for a complete sync
    ##
    syncTimeout: 30

    ## the name of a pre-created Secret with git ssh credentials
    ##
    sshSecret: super-secret-ssh

    ## the key in `dags.gitSync.sshSecret` with your ssh-key file
    ##
    sshSecretKey: id_rsa

    ## the string value of a "known_hosts" file (for SSH only)
    ## - [WARNING] known_hosts verification will be disabled if left empty, making you more
    ##   vulnerable to repo spoofing attacks
    ##
    ## ____ EXAMPLE _______________
    ##   sshKnownHosts: |-
    ##     <HOST_NAME> ssh-rsa <HOST_KEY>
    ##
    ## sshKnownHosts: ''

    ## the number of consecutive failures allowed before aborting
    ##  - the first sync must succeed
    ##  - a value of -1 will retry forever after the initial sync
    ##
    maxFailures: 0
```

So, is there anything that I'm doing wrong? Please, let me know if you need some more information
