### ISSUE TITLE
allow sparse checkout with `git-sync`

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#431]
Currently, we provide `dags.gitSync.repoSubPath`, but even if this is set, the full repo is cloned (it only prevents airflow from seeing the rest of the repo).

As of `v3.1.1` the [kubernetes/git-sync](https://github.com/kubernetes/git-sync) container supports using [git sparse-checkout files](https://git-scm.com/docs/git-sparse-checkout#_sparse_checkout) with the `GIT_SYNC_SPARSE_CHECKOUT_FILE` config.

__We should add a new value `dags.gitSync.sparseCheckoutFile` so that users can specify which files they want to incldue/exclude.__
```yaml
dags:
  gitSync:
    ## we will NOT automatically exclude everything if `repoSubPath` is set 
    ## (current users might depend on the presence of other files, while setting `repoSubPath`)
    repoSubPath: /my_dags/

    ## include files under `/my_dags/`, but not `/my_dags/big_files/`
    sparseCheckoutFile: |
      /my_dags/*
      !/my_dags/big_files/*
```
