### ISSUE TITLE
add values to disable git-sync sidecars for specific deployments

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#437]
Currently, if a user sets `dags.gitSync.enabled = true` then all deployments get a git-sync sidecar, (including [deployments like the webserver](https://github.com/airflow-helm/charts/blob/a55c4cd280f5aebef5c0dff9631e18a9fa23fc93/charts/airflow/templates/webserver/webserver-deployment.yaml#L143-L145) which don't actually need the DAGs as of airflow 2.0).

We do this because some users are storing "python packages" or "airflow plugins" in their dags folder. For example, if you set `AIRFLOW__CORE__XCOM_BACKEND` to something in the git-sync folder, airflow will fail to start (and fail to `import airflow`) if that folder is missing (see https://github.com/airflow-helm/charts/issues/245).

__For users who want to explicitly disable git-sync in most deployments, we should provide some new values:__
```yaml
dags:
  gitSync:
    enabled: true

    ## new values (only applicable if `dags.gitSync.enabled = true`)
    disableFor:
      webserver: false
      flower: false
      dbMigrations: false
      sync: false
```
