### ISSUE TITLE
Dag_id could not found in KubernetesExecutor mode

### ISSUE THREAD

**Issue by nguyenkien1402** [airflow-helm/charts#45]
**What is the bug?**
Hi everyone,
I am running stable/airflow on Azure Kubernetes with git-sync enable.
The example dags work just fine but not the dag in the Bitbucket repo.
My dag is pretty simple like this for testing purpose:

```
default_args = {
    'owner': 'Dev',
    'start_date': days_ago(2)
}

with DAG(
    dag_id='myown_example_kubernetes_executor_config',
    default_args=default_args,
    schedule_interval=None
) as dag:

    def print_stuff():
        print("Print stuff")

    # You can use annotations on your kubernetes pods!
    start_task = PythonOperator(
        task_id="start_task",
        python_callable=print_stuff,
        executor_config={
            "KubernetesExecutor": {
                "annotations": {"test": "annotation"}
            }
        }
    )

```
and the structure of Bitbucket repo like this:
![image](https://user-images.githubusercontent.com/9146421/102740063-ef17a800-43a2-11eb-8255-23dd0b7e5c0d.png)

I get the error from the pod when I trigger the dag:
![image](https://user-images.githubusercontent.com/9146421/102740108-1b332900-43a3-11eb-87e9-f59ea7df48ee.png)

I ssh into the airflow-web to the dags and it is there.
![image](https://user-images.githubusercontent.com/9146421/102740177-52093f00-43a3-11eb-9d68-52fc108dccdc.png)

**What are your Helm values?**

```
airflow:
  image:
    repository: apache/airflow
    tag: 1.10.12-python3.6
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""

  executor: KubernetesExecutor
  
  fernetKey: "PhyRqLI_7aoFYH4sTxtapY1xSTAAuZGU_dbntcUdUeI="

  config:
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags/dags"
      AIRFLOW__CORE__REMOTE_LOGGING: "True"
      AIRFLOW__CORE__REMOTE_LOG_CONN_ID: my_aws
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://airflow-logs-kube"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://<usernamne>@ppsdb:<password>@<host>.database.azure.com:5432/postgres"
      AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS: "True"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
      AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.12"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
      AIRFLOW__KUBERNETES__GIT_REPO: "git@bitbucket.org:ryanntk/k8s_airflow.git"
      AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags/dags"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: "airflow-git-keys"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "True"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
      AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"

  extraEnv:
    - name: AIRFLOW__KUBERNETES__GIT_SYNC_RUN_AS_USER
      value: "65533"

scheduler:
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"

  connections:
    - id: my_aws
      type: aws
      extra: |
        {
           "aws_access_key_id": "<aws_id>",
           "aws_secret_access_key": "<aws_key>",
           "region_name":"ap-southeast-2"
        }
  variables: |
    {}
  pools: |
    {}
  initdb: true
  initialStartupDelay: 0

web:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
  replicas: 1
  service:
    annotations: {}
    type: LoadBalancer
    externalPort: 8080
    loadBalancerSourceRanges: []
  baseUrl: "http://airflow.azure:8080"
  livenessProbe:
    enabled: true
    scheme: HTTP
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 2


workers:
  enabled: false

flower:
  enabled: false

logs:

  path: /opt/airflow/logs
  persistence:
    enabled: false
    subPath: ""
    storageClass: ""
    accessMode: ReadWriteMany
    size: 1Gi

dags:
  doNotPickle: true
  persistence:
    enabled: false
    subPath: ""
    storageClass: ""
    accessMode: ReadOnlyMany
    size: 1Gi

  git:
    url: "git@bitbucket.org:ryanntk/k8s_airflow.git"
    ref: master
    secret: airflow-git-keys
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "bitbucket.org"
    repoPort: 22
    gitSync:
      enabled: true
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60
  initContainer:
    enabled: true
	

ingress:
  enabled: false

rbac:
  create: true
  events: false
  
serviceAccount:
  create: true
  name: ""
  annotations: {}

extraManifests: []

postgresql:
  enabled: false


externalDatabase:

  type: postgres
  host: <host>.database.azure.com
  port: 5432
  database: postgres
  user: <usrename>
  passwordSecret: airflow-postgres-password
  passwordSecretKey: postgres-password
  properties: ""

redis:
  enabled: false

serviceMonitor:
  enabled: false


prometheusRule:
  enabled: false
```

**What is your Kubernetes Version?**:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Any help would be very much appreciated
