### ISSUE TITLE
DB migrations deployment is stuck after new deployment

### ISSUE THREAD

**Issue by karakanb** [airflow-helm/charts#457]
**What is the bug?**

It seems like when there are no more migrations to run, the `db-migrations` deployment is getting stuck for some reason:
```
❯ stern airflow-v2-db-migrations-5bcd44b54c-n9j8k
+ airflow-v2-db-migrations-5bcd44b54c-n9j8k › dags-git-sync
+ airflow-v2-db-migrations-5bcd44b54c-n9j8k › db-migrations
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:357 DeprecationWarning: The dag_concurrency option in [core] has been renamed to max_active_tasks_per_dag - the old setting has been used, but please update your config.
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-microsoft-mssql uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-ssh uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-tableau uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations [2021-11-03 01:08:25,563] {providers_manager.py:152} WARNING - Exception when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package: No module named 'plyvel'
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/azure/cosmos/session.py:186 SyntaxWarning: "is not" with a literal. Did you mean "!="?
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/azure/storage/common/_connection.py:82 SyntaxWarning: "is" with a literal. Did you mean "=="?
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-microsoft-mssql uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-ssh uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations /home/airflow/.local/lib/python3.8/site-packages/airflow/providers_manager.py:517 DeprecationWarning: The provider apache-airflow-providers-tableau uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations [2021-11-03 01:08:27,202] {providers_manager.py:152} WARNING - Exception when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package: No module named 'plyvel'
airflow-v2-db-migrations-5bcd44b54c-n9j8k db-migrations [2021-11-03 01:08:27,297] {db_migrations.py:56} INFO - there are no unapplied db migrations, continuing...
airflow-v2-db-migrations-5bcd44b54c-n9j8k dags-git-sync INFO: detected pid 1, running init handler
airflow-v2-db-migrations-5bcd44b54c-n9j8k dags-git-sync I1103 01:08:15.696503      13 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=13
```

**What version of the chart are you using?**:

I am using version `8.5.2`

**What is your Kubernetes Version?**:

```console
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
❯ helm version           
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

**Please copy your custom Helm values file:**

```yaml
airflow:
    fernetKey: "some-key"
    executor: KubernetesExecutor
    users: []
    image:
        repository: some-host
        tag: latest
        pullSecret: gitlab-pull-secret
    
    config:
        ## Security
        AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
        AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
        AIRFLOW__WEBSERVER__RBAC: "True"
        AIRFLOW__WEBSERVER__SECRET_KEY: "some-secret"

        AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"
        AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo"
        AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"

        ## DAGS
        AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
        
        ## Core
        AIRFLOW__CORE__SECURE_MODE: "True"
        AIRFLOW__CORE__LOAD_EXAMPLES: "False"
        AIRFLOW__CORE__PARALLELISM: "10"
        AIRFLOW__CORE__DAG_CONCURRENCY: "5"
        AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "1"

        ## Email (SMTP)
        AIRFLOW__EMAIL__EMAIL_BACKEND: "airflow.utils.email.send_email_smtp"
        AIRFLOW__SMTP__SMTP_HOST: "smtpmail.example.com"
        AIRFLOW__SMTP__SMTP_STARTTLS: "False"
        AIRFLOW__SMTP__SMTP_SSL: "False"
        AIRFLOW__SMTP__SMTP_PORT: "25"
        AIRFLOW__SMTP__SMTP_MAIL_FROM: "admin@example.com"

        ## Disable noisy "Handling signal: ttou" Gunicorn log messages
        GUNICORN_CMD_ARGS: "--log-level WARNING"

    kubernetesPodTemplate:
        resources:
            requests:
                cpu: "200m"
                memory: "250Mi"
            limits:
                cpu: "400m"
                memory: "500Mi"

logs:
    path: /opt/airflow/logs
    persistence:
        enabled: true
        storageClass: nfs

workers:
    enabled: false

flower:
    enabled: false

redis:
    enabled: false

dags:
    path: /opt/airflow/dags
    gitSync:
        enabled: true
        repo: "some-repo-url"
        sshSecret: "some-secret-name"
        sshSecretKey: "some-key-name"
        depth: 0

web:
    replicas: 1

ingress:
    enabled: true
    web:
        host: "example.com"
        annotations:
            nginx.ingress.kubernetes.io/affinity: cookie

postgresql:
    enabled: false

externalDatabase:
    type: postgres
    host: some-host
    port: some-port
    database: some-db
    user: some-user
    passwordSecret: some-secret
    passwordSecretKey: some-key
    properties: some-properties


serviceMonitor:
  enabled: false

prometheusRule:
  enabled: false

pgbouncer:
  enabled: false
```

I have obfuscated some bits of the values file, but it is pretty generic.
