### ISSUE TITLE
Unable to initialize the pod 

### ISSUE THREAD

**Issue by nguyenkien1402** [airflow-helm/charts#46]
Hi guys,
I am losing my hair chasing the issue on KubernetesExecutor with git-sync.

The issue is I the pod is not able to initialize to run. It always gives me this **Init:Error**

Here is my **values.yaml**

```
airflow:
  ## configs for the docker image of the web/scheduler/worker
  ##
  image:
    repository: apache/airflow
    tag: 1.10.12-python3.6
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""

  executor: KubernetesExecutor


  fernetKey: "PhyRqLI_7aoFYH4sTxtapY1xSTAAuZGU_dbntcUdUeI="

  config:
      AIRFLOW__CORE__REMOTE_LOGGING: "True"
      AIRFLOW__CORE__REMOTE_LOG_CONN_ID: my_aws
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://airflow-logs-kube"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.12-python3.6"
      AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
      AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE: "10"
      AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
      AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
      AIRFLOW__KUBERNETES__GIT_REPO: "git@bitbucket.org:ryanntk/k8s_airflow.git"
      AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
      AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/opt/airflow/dags"
      AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"

      AIRFLOW__KUBERNETES__GIT_SSH_KEY_SECRET_NAME: airflow-git-keys
      AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
      AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "False"
      AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"


###################################
# Airflow - DAGs Configs
###################################
dags:
  path: /opt/airflow/dags
  doNotPickle: false
  installRequirements: true

  git:
    url: "git@bitbucket.org:ryanntk/k8s_airflow.git"
    ref: master
    secret: airflow-git-keys
    sshKeyscan: true
    privateKeyName: id_rsa
    repoHost: "bitbucket.org"
    repoPort: 22

    gitSync:
      enabled: true
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: Always
      refreshTime: 60

  initContainer:
    enabled: true
    image:
      repository: alpine/git
      tag: latest
      pullPolicy: Always
    mountPath: "/opt/airflow/dags"
....
```

If I trigger the dag, here is what I get 
![image](https://user-images.githubusercontent.com/9146421/102839417-930d5c00-4454-11eb-96cd-fe5a342a881e.png)

Any help would be very much appreciated 💯
