### ISSUE TITLE
Add pod lifecycle options

### ISSUE THREAD

**Issue by c-thiel** [airflow-helm/charts#463]
**What is your feature request?**
In the Chart we currently don't have an option to add a lifecycle to the pods. 
These lifecycle hooks can be useful in a number of situations where we need to patch small parts of the pod.
An example could be:
```
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", do_something.sh]
```

To give a concrete example, I am currently facing this issue https://github.com/apache/airflow/issues/8212.
To fix this I need to patch a single file in the container. I could of course go ahead and build my custom container - having a lifecycle hook would be very simple though.

Implementation should be really simple and straight forward - just forwarding whatever the user specifies in the values.yaml.

It would be good to have this, as anything else, once globally and additionaly an option to overwrite for the individual components.
