### ISSUE TITLE
Allow specification of RollingUpdate specification

### ISSUE THREAD

**Issue by c-thiel** [airflow-helm/charts#465]
## What is your feature request?

Currently the Update Strategy is fixed to RollingUpdate (which is reasonable I think).
What is missing is the specification of the rollingUpdate:

```yaml
strategy:
  type: RollingUpdate
  # This bit is missing:
  rollingUpdate:
     maxUnavailable: 25%
     maxSurge: 1
```

I am running a very large Airflow Deployment with hundreds of worker pods in production. As I currently have no option to specify the rolling Update behaviour, one pod is updated at a time. This takes a very long time.

It would be great if we could add to `values.yaml`:

```yaml
updateStrategy:
  type: RollingUpdate
  ## Optionally specify rolling update strategy
  # rollingUpdate:
  #   maxUnavailable: 25%
  #   maxSurge: 1
```

In the templates we could then just use a `toYaml` of the user specified block.
