### ISSUE TITLE
workers extraVolumes and extraVolumes get stuck in init state

### ISSUE THREAD

**Issue by chuyuou** [airflow-helm/charts#469]
## What version of the chart are you using?

I am using version `1.0.0` and `1.3.0` of this chart.

## What version of Kubernetes are you using?
``` 
 Client Version: v1.18.6
Server Version: v1.20.10-gke.1600
 ```

## What version of Helm are you using?

```console
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
    defaultSecurityContext:
      fsGroup: 0
      runAsGroup: 0
    logs:
      persistence:
        enabled: true
        existingClaim: logs
    images:
      airflow:
        repository: mydocker/airflow-custom
        #repository: apache/airflow
        tag: kube_v3
        pullPolicy: Always
    registry:
      secretName: dockerconfigjson
    webserverSecretKey: webserver-secret
    webserver:
      allowPodLogReading: true
    scheduler:
      extraInitContainers:
        - name: fix-volume-logs-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 50000:0 /opt/airflow/logs/" ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /opt/airflow/logs/
              name: logs
    workers:
      extraVolumes:
        - name: google-service-secret
          secret:
            secretName: google-service-secret
      extraVolumeMounts:
        - name: google-service-secret
          mountPath: /opt/airflow/secrets 
          readOnly: true
```
I used the extraVolumeMounts config for workers as the documentation, but workers pods stuck in init state and couldn't propceed. Am I missing anything?

**Comment by thesuperzapper** [comment]
@chuyuou If you describe the pod that is stuck in init, what are its events?

Also, what are the logs for the init container (which I assume is failing)?

**Comment by chuyuou** [comment]
Hi, thanks for replying!! 

I got it working by writing as 
```
  values:
    workers:
      extraVolumeMounts:
        - name: google-cloud-key
          mountPath: /opt/airflow/secrets
      extraVolumes:
        - name: google-cloud-key
          secret:
            secretName: google-service-secret
```
without `readOnly: true`.
