### ISSUE TITLE
How to set connection extras

### ISSUE THREAD

**Issue by jherrmannNetfonds** [airflow-helm/charts#471]
I am trying to set extra connection fields for example for google_cloud_platform:

```
airflow:
  connections:
    - id: google_cloud_default
      type: google_cloud_platform
      description: google cloud connection
      extra: |-
        { "extra__google_cloud_platform__key_path": "/path/to/key.json", "extra__google_cloud_platform__project: "project-12345", "extra__google_cloud_platform__num_retries": "5" }
```
after helm install the values (Keyfile Path and Project Id) are not set in the UI. Same for extras of other connections types like kubernetes.
Is there a special syntax I have to follow?

**Comment by thesuperzapper** [comment]
@jherrmannNetfonds what you are doing should work?

Are you seeing any errors on the `snyc-connections` deployment pods?

**Comment by jherrmannNetfonds** [comment]
Hi @thesuperzapper thx for reply and the great work on the chart.
I will check the logs on my next deployment. Did not thing about them yet.

**Comment by thesuperzapper** [comment]
@jherrmannNetfonds do you mean `airflow.connectionsUpdate` (with the `airflow.` prefix)?

**Comment by jherrmannNetfonds** [comment]
@thesuperzapper correct:

```
###################################
# Airflow - Common Configs
###################################
airflow:
  legacyCommands: false

  executor: KubernetesExecutor

  usersUpdate: false
  connectionsUpdate: false
  variablesUpdate: false
```

I will try to recreate the issue with a minimum example.
