### ISSUE TITLE
Airflow connection is added with the missing fields

### ISSUE THREAD

**Issue by nerilau** [airflow-helm/charts#474]
## What is the bug?

The bug is that connection is being created, but host, port and login variables are missing and only extra, connection type, password, and description are discovered. Also, when I execute helm template command I can see the following output in the `job-scripts` secret which indicates that values are provided correctly:
```python
    connections = [
      Connection(
        conn_id="ssh_connection",
        conn_type="ssh",
        description="Airflow ssh connection",
        host="provided_host",
        login="provided_login",
        password="provided_password",
        port=22,
        extra="{\n  \"key_file\": \"/path_to_key\"\n}",
      ),
    ]

    for c in connections:
      with create_session() as session:
        query_result = session.query(Connection).filter(Connection.conn_id == c.conn_id).first()
        if not query_result:
          session.add(c)
          print(f"Connection=`{c.conn_id}` was successfully added.")
        else:
          if compare_connections(c, query_result):
            print(f"Connection=`{c.conn_id}` already exists as defined, skipping.")
          else:
            print(f"Connection=`{c.conn_id}` already exists but has changed, updating...")
            query_result.conn_type = c.conn_type
            query_result.description = c.description
            query_result.host = c.host
            query_result.login = c.login
            query_result.password = c.password
            query_result.schema = c.schema
            query_result.port = c.port
            query_result.extra = c.extra
            print(f"Connection=`{c.conn_id}` was successfully updated.")

```

## What version of the chart are you using?

I am using version `8.0.8` of this chart.

## What version of Kubernetes are you using?

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}.
```

## What version of Helm are you using?

```console
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
airflow:
{{- with secret "secret/airflow/env" }}
  connections:
  - id: ssh_connection
    type: ssh
    description: Airflow ssh connection
    host: {{ .Data.ssh_host }}
    port: 22
    login: {{ .Data.ssh_username }}
    password: {{ .Data.ssh_password }}
    extra: |-
      {
        "key_file": "/path_to_key"
      }
{{- end }}
```

</details>
