### ISSUE TITLE
Error if `ingress.web.precedingPaths[].servicePort` is specified as a string

### ISSUE THREAD

**Issue by chaudharishalmali** [airflow-helm/charts#477]
## What is the bug?

There seems to be an issue with the webserver ingress configuration of the chart. I've added few annotations to my ingress configuration in the values.yaml. When I add "use-annotation" to servicePort of my precedings path, I get an error saying 

got "string", expected "integer"
![image](https://user-images.githubusercontent.com/28332830/143923362-cf54fe6a-8a0b-46ae-8c8a-1dc5563347fe.png)

I believe it used to work without problem for the apiVersion: networking.k8s.io/v1beta1, but with the new version networking.k8s.io/v1 I suppose we can either give port number or port name. 

This line from the webserver-ingress template seems to be using number instead of name which is why I think we won't be able to tell ssl-redirect service to use-annotation's instead.
https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-ingress.yaml#L39

I see ithe official airflow helm chart have made a change where they have specified the servicePort to be name instead of number. Can similar change be done for this chart as well? 
https://github.com/apache/airflow/blob/main/chart/templates/webserver/webserver-ingress.yaml#L64

Please let me know if I'm mistaken with my usage of annotations for the ingress configuration.

## What version of the chart are you using?

I am using version `8.5.2` of this chart.
![image](https://user-images.githubusercontent.com/28332830/143925373-0bb829a7-dcb5-4a71-a29c-2bf1b29b6d26.png)

## What version of Kubernetes are you using?

```console
######## PASTE `kubectl version` BELOW ########
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version:  version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
######## PASTE `kubectl version` ABOVE ########
```

## What version of Helm are you using?

```console
######## PASTE `helm version` BELOW ########
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
######## PASTE `helm version` ABOVE ########
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
######## PASTE values.yaml BELOW ########
airflow:
  ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  web:
    host: "example.com"
    path: "/airflow"
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:XXXXXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"type": "redirect", "redirectConfig": { "protocol": "HTTPS", "port": "443", "host": "example.com", "Path": "/airflow", "Query": "k=v", "StatusCode": "HTTP_301
"}}'
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-path: '/health'
      alb.ingress.kubernetes.io/success-codes: 200,201,300,301
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    precedingPaths:
      - path: "/*"
        serviceName: "ssl-redirect"
        servicePort: "use-annotation"
######## PASTE values.yaml ABOVE ########
```

</details>
