### ISSUE TITLE
add ability to extend airflow RBAC verbs with `rbac.extraRules`

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#495]
As raised by @pindge in https://github.com/airflow-helm/charts/issues/334, sometimes users need to add extra RBAC verbs for things like custom airflow operators.

We should add a value like `rbac.extraRules` that allows users to merge their own RBAC rules into our pre-generated ones, for example:
```yaml
rbac:
  extraRules:
    - apiGroups:
      - "batch"
      - "extensions"
      resources:
      - jobs
      verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
```

__NOTE:__ we will have to be careful to de-dupe between the default and user-provided rules (using some clever helm templating).
