### ISSUE TITLE
Service Port Naming Not Compatible with Istio

### ISSUE THREAD

**Issue by danattatari** [airflow-helm/charts#499]
## What is the bug?

[pgbouncer](https://raw.githubusercontent.com/airflow-helm/charts/main/charts/airflow/templates/pgbouncer/pgbouncer-service.yaml), [worker](https://raw.githubusercontent.com/airflow-helm/charts/main/charts/airflow/templates/worker/worker-service.yaml), and [web](https://raw.githubusercontent.com/airflow-helm/charts/main/charts/airflow/templates/webserver/webserver-service.yaml) have static service port names that are incompatible with [Istio naming conventions](https://istio.io/latest/docs/reference/config/analysis/ist0118/). 

__Note:__ I have a [PR](https://github.com/airflow-helm/charts/pull/493) to address it

## What version of the chart are you using?

I am using version `8.5.2` of this chart.

## What version of Kubernetes are you using?

```console
Client Version: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

## What version of Helm are you using?

```console
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
######## PASTE values.yaml BELOW ########
airflow:
  airflow:
    config:
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://bucket/airflow-test"
      AIRFLOW__WEBSERVER__BASE_URL: "https://xxx.example.dev"

      ENV: staging
  dags:
    gitSync:
      branch: "staging"
  ingress:
    web:
      host: "xxx.example.dev"
  workers:
    replicas: 2
  postgresql:
    persistence:
      size: 20Gi
      existingClaim: existing-claim-
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::1234567890:role/this-role"
  ...
######## PASTE values.yaml ABOVE ########
```

</details>
