### ISSUE TITLE
support additional pgbouncer configuration

### ISSUE THREAD

**Issue by pindge** [airflow-helm/charts#500]
## What is your feature request?

I would like the chart to support additional configuration for `pgbouncer` service https://www.pgbouncer.org/config.html#example

useful custom config include:
- `admin_users` https://github.com/pgbouncer/pgbouncer/blob/master/etc/pgbouncer.ini#L129-L130
- `ignore_startup_parameters` https://github.com/pgbouncer/pgbouncer/blob/master/etc/pgbouncer.ini#L154-L156 

## Attempted solution

```
extraContainers:
        - name: pgbouncer-exporter
          image: prometheuscommunity/pgbouncer-exporter:v0.4.0
          imagePullPolicy: IfNotPresent
          args:
            - --web.listen-address=9127
            - --web.telemetry-path=/metrics
            - --log.level=info
            - --log.format=logfmt
            - --pgBouncer.connectionString=postgres://airflow:$(db_password)@airflow-pgbouncer:6432/pgbouncer?sslmode=disable&connect_timeout=10
          ports:
            - name: exporter
              containerPort: 9127
              protocol: TCP
          resources:
            requests:
                cpu: 10m
                memory: 128Mi
          env:
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: airflow-db
                  key: postgres-password
```

And this was the error 
```
+ kubectl logs airflow-web-78c7cf4f4-mzgfl -n processing -c pgbouncer-exporter
level=error ts=2022-01-11T00:38:28.718Z caller=collector.go:129 msg="error setting up DB connection" err="error pinging pgbouncer: \"pq: not allowed\""
```
## What alternatives have you considered?

Alternatively the chart could...
