### ISSUE TITLE
add log-cleanup sidecar to scheduler/worker pods

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#502]
Right now, if worker/scheduler pods run for long periods of time, they may accumulate so many logs under `logs.path` that they may cause issues.

We should allow users to deploy a sidecar that is responsible to truncate log files after some period of time.

__Here are some example values for what this feature may look like:__
```yaml
scheduler:
  logCleanup:
    # if the sidecar container is added to the scheduler Pod (default: true)
    enabled: true

    # resources for the ContainerSpec
    resources: {}

    # number of seconds to retain log files after their last-modified time (default: 15 days)
    retention: 21600

    # number of seconds between each truncation loop (default: 15 min)
    interval: 900 

workers:
  logCleanup:
    ## SAME AS ABOVE
```

__WARNING:__ we should NOT allow `{scheduler,workers}.logCleanup.enabled` and `logs.persistence.enabled` to be true at the same time (using `./_helpers/validate-values.tpl`) as multiple of the sidecars may fight with each other. In the error message, tell users that they could create an airflow job instead.
