### ISSUE TITLE
Add section on how to add credentials to authenticate with private repository

### ISSUE THREAD

**Issue by upliftertom** [airflow-helm/charts#504]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Description

I spent some time trying to get a custom private image working which included my python packages, because I couldn't find where to set my registry credentials.

It was obvious when I found it in the values.yaml at:

```yaml
# Auth secret for a private registry
# This is used if pulling airflow images from a private registry
registry:
  secretName: 

  # Example:
  # connection:
  #   user: ~
  #   pass: ~
  #   host: ~
  #   email: ~
```

but when I was reading through the docs I didn't manage to find any reference to including/updating this.  

A section on setting this might be beneficial for others getting started- maybe on the Production Guide or Configuring Airflow pages?   

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [ ] I can provide feedback!

**Comment by thesuperzapper** [comment]
@upliftertom I believe this issue is for another chart, as this chart uses values like the following:

```yaml
airflow:
  image:
    pullSecret: ""
```
