### ISSUE TITLE
git-sync container restarts

### ISSUE THREAD

**Issue by DenysKunak** [airflow-helm/charts#513]
We have Airflow setup on Kubernetes.
Currently our git repo performs a maintenance once a day, which causes airflow git-sync container to fail with error 503 and restart itself and the whole worker/web/scheduler pod.

Error looks like the following:
"msg"="too many failures, aborting" "error"="Run(git ls-remote -q origin refs/heads/develop): exit status 128: { stdout: \"\", stderr: \"Bitb ││ ucket is currently unavailable:\\n- The system is unavailable while maintenance is being performed.\\n- Bitbucket is unavailable while it is being backed up\\nfatal: Could not read from ││  remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\" }"  "failCount"=0

Is there a way to prevent git-sync container restart on occasions when git repo is not reachable?

**Comment by thesuperzapper** [comment]
@DenysKunak you can set the `dags.gitSync.maxFailures` to a non `0` value, this will allow a certain number of failures before the git-sync container restarts.

```yaml
dags:

  ## configs for the git-sync sidecar (https://github.com/kubernetes/git-sync)
  ##
  gitSync:

    ## the number of consecutive failures allowed before aborting
    ##  - the first sync must succeed
    ##  - a value of -1 will retry forever after the initial sync
    ##
    maxFailures: 0

```
