### ISSUE TITLE
How to correctly configure lineage backend using the chart

### ISSUE THREAD

**Issue by rodolfo-picoreti** [airflow-helm/charts#519]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] I have looked through the [FAQ](https://github.com/airflow-helm/charts/tree/main/charts/airflow#faq---airflow).

### Question

Hi everyone,

I am trying to use datahub lineage backend on airflow. The datahub documentation says that it should be configured via airflow.cfg file. But this chart do not expose this option.

Example Config:
```
[lineage]
backend = datahub_provider.lineage.datahub.DatahubLineageBackend
datahub_kwargs = {
    "datahub_conn_id": "datahub_rest_default",
    "cluster": "prod",
    "capture_ownership_info": true,
    "capture_tags_info": true,
    "graceful_exceptions": true }
```

I found that I can configure the backend via AIRFLOW__LINEAGE__BACKEND env var. But what about the **datahub_kwargs**? It is only possible to configure it via env var if the maintainers add this option here: https://github.com/linkedin/datahub/blob/9bdc9af7b90c6a97194eceb898543360b4eb105c/metadata-ingestion/src/datahub_provider/lineage/datahub.py#L27 ?

**Comment by thesuperzapper** [comment]
@rodolfo-picoreti are you sure that `AIRFLOW__LINEAGE__DATAHUB_KWARGS`  will not work?

Just encode your JSON into a string:

```yaml
airflow:
  config:
    AIRFLOW__LINEAGE__DATAHUB_KWARGS: >-
      { 
          "datahub_conn_id": "datahub_rest_default",
           "cluster": "prod",
           "capture_ownership_info": true,
           "capture_tags_info": true,
           "graceful_exceptions": true 
       }
```
