### ISSUE TITLE
some helm templates can not be used in `extraManifests`

### ISSUE THREAD

**Issue by joeybaer** [airflow-helm/charts#522]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] I have looked through the [FAQ](https://github.com/airflow-helm/charts/tree/main/charts/airflow#faq---airflow).

### Question

Chart Version: 8.1.1
Helm Version: 3.8.0

We are wanting to leverage the `extraManifests` to run a job that has access to the airflow config environment and secrets. 

Going off of the example:

```
  extraManifests:
   - apiVersion: cloud.google.com/v1beta1
     kind: BackendConfig
     metadata:
       name: "{{ .Release.Name }}-test"
     spec:
       securityPolicy:
         name: "gcp-cloud-armor-policy-test"
```

Referencing dynamic string values like `{{.Release.Name}}` and even helper functions ( named templates ) like  `'{{ include "airflow.labels.app" . }}'`  work great as long as the helper returns in a string value.

Where I have been unable to find a clear solution is when trying things like `{{ include "airflow.env" . | indent 10}}` which returns a multi line yaml and cannot be quoted since it would change the structure of the resulting json when converted to a Kubernetes object.

I have tried a few different ways, such as trying to pass the entire object as a string like below but also using the different multi line scalars such as `|` and `>` with the thought being if I can pass each list item as a full string then the [extra-manifests template](https://github.com/airflow-helm/charts/blob/airflow-8.1.1/charts/airflow/templates/extra-manifests.yaml) will do all the magic

```
  extraManifests:
   - 'apiVersion: cloud.google.com/v1beta1
     kind: BackendConfig
     metadata:
       name: "{{ .Release.Name }}-test"
     spec:
       securityPolicy:
         name: "gcp-cloud-armor-policy-test"
    testKey: {{ include "airflow.env" . }}'
```

Unfortunately the above results in the following error:
```
Error: YAML parse error on airflow/templates/extra-manifests.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
```

Also a thing to note is if you don't quote the interpolated values like `{{ var }}` you will get errors like the following:
```
Error: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"include \"airflow.labels.app\" .":interface {}(nil)}
```

How I am testing to get the above errors:
```
helm template --debug airflow-stable/airflow \
  --namespace test-namespace \
  --version 8.1.1 \
  --values test-values.yaml \
  -s templates/extra-manifests.yaml
```

Has anyone encountered this before? Is there a viable solution and just a syntax lesson here? If anyone has any other way they are solving providing all the env/secret context to additional jobs/pods please share :D
