### ISSUE TITLE
replace PGBouncer's readinessProbe with startupProbe

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#526]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Motivation

There are a number of reports where people are having "connection refused" issues with their pgbouncer:
- https://github.com/airflow-helm/charts/issues/525
- https://github.com/airflow-helm/charts/issues/492

These issues are caused by intermittent failures in the `readinessProbe` (probably timeouts) causing the pod to become "unready" which means that `airflow-pgbouncer.{NAMESPACE}.svc.cluster.local` no longer resolves to an IP address, leading to the `livenessProbe` having "connection refused" and the pod restarting.

### Implementation

While we could just remove the [`readinessProbe`](https://github.com/airflow-helm/charts/blob/df99a33e3278de9f6935e747e8317794966ed979/charts/airflow/templates/pgbouncer/pgbouncer-deployment.yaml#L119-L125), this could result in downtime during rolling updates, when two pods might exist at the same time, and the new pod may not be ready to receive connections yet.

Instead, we can replace the `readinessProbe` with a `startupProbe`, so that traffic is not sent to the pod before it is ready, but that readiness probe failures/timeouts don't cascade and cause the `livenessProbe` to fail.

The startup probe might look like this:

```yaml
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 30
            tcpSocket:
              port: 6432
```

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!
