### ISSUE TITLE
allow `airflow.users[].roles` to specify a list of roles

### ISSUE THREAD

**Issue by kmehkeri** [airflow-helm/charts#538]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Motivation

Currently user defined via `values.yaml` can only be granted a single role. If more roles are assigned (via UI/API), sync process will revoke them as soon as it runs again.

I would like to be able to specify multiple roles in array:
```yaml
users:
  name: some_user
  role: [User, SpecialRoleA, SpecialRoleB]
```

`role` attribute should support both single value and an array, for backwards compatibility.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!
