### ISSUE TITLE
add `airflow.defaultContainerSecurityContext` value 

### ISSUE THREAD

**Issue by heba920908** [airflow-helm/charts#578]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

After enabling gatekeeper admission controller for pod security policies `Should not allow container privilege escalation (deny)`, gatekeeper will not allow creation of new pods which does not have specified `spec.containers[*].securityContext.allowPrivilegeEscalation=false`

[Azure policy](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Kubernetes/ContainerNoPrivilegeEscalation.json)
[Gatekeeper Library](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/allow-privilege-escalation/template.yaml#L52)

From [k8s security context docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) and motivation for policy:

_allowPrivilegeEscalation: Controls whether a process can gain more privileges than its parent process. This bool directly controls whether the [no_new_privs](https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt) flag gets set on the container process. allowPrivilegeEscalation is *always true*_

Policy rego current implementation part:

```text
## allowPrivilegeEscalation=true                                                                                                  │
│ ## runAsUser != 0 + missing allowPrivilegeEscalation=false 

input_allow_privilege_escalation(c) {                                                                                             │
│     not c.securityContext.allowPrivilegeEscalation == false                                                                       │
│     not c.securityContext.runAsUser                                                                                               │
│     input.review.object.spec.securityContext.runAsUser != 0                                                                       │
│ }   
```

Being that stated, if we try to install as it is the community airflow helm release with gatekeeper admission controller and psp enabled, following errors will appear (for all airflow pods):

```text
0s          Warning   FailedCreate                 replicaset/airflow2-scheduler-66ffcdc9df                 Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [azurepolicy-psp-container-no-privilege-esc-e6a74aee95507167737f] Privilege escalation container is not allowed: airflow-scheduler...
```

Current implementation does not have the optional `containerSecurityContext` spec, and it is being hardcoded in helper [pods.tpl](https://github.com/airflow-helm/charts/blob/airflow-8.6.0/charts/airflow/templates/_helpers/pods.tpl#L7)

Unfortunately the `containerSecurityContext` cannot be modified in the community helm chart, we even tried with the `Values.DefaultSecurityContext`, nevertheless, does not have good outcome that way, If we plan to add the `allowPrivilegeEscalation: false` in `podSecurityContext`, will see errors while deploying helm chart.

```text
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext
```

Would be nice to have some optional value for `containerSecurityContext`.

### Implementation

To enable `containerSecurityContext.allowPrivilegeEscalation` option in the values.

Modify [pods.tlp](https://github.com/airflow-helm/charts/blob/airflow-8.6.0/charts/airflow/templates/_helpers/pods.tpl#L7):

```yaml
{{- define "airflow.image" }}
image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
securityContext:
  runAsUser: {{ .Values.airflow.image.uid }}
  runAsGroup: {{ .Values.airflow.image.gid }}
{{- range $key, $value := .Values.airflow.containerSecurityContext }}
  {{- if and (not (eq $key "runAsUser")) (not (eq $key "runAsGroup")) }}
  {{ $key }}: {{ $value }} 
  {{- end }}
{{- end }}
{{- end }}
```

__Current Code__: [airflow-8.5.2 - pods.tpl](https://github.com/airflow-helm/charts/blob/airflow-8.6.0/charts/airflow/templates/_helpers/pods.tpl#L7)

In the [values.yaml](https://github.com/airflow-helm/charts/blob/airflow-8.6.0/charts/airflow/values.yaml), we need to add the following to comply with policy:

```yaml
airflow:
  airflow:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      foo: bar
      # runAsUser and runAsGroup will not be noted since will be grabbed from .Values.airflow.image.uid and .Values.airflow.image.gid
```

`runAsUser` and `runAsGroup` will be ignored since will be configured from `.Values.airflow.image.uid` and `.Values.airflow.image.gid`

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@heba920908 thanks for raising this issue!

I think we resolve this by creating a value called `airflow.defaultContainerSecurityContext`, for example:

```yaml
airflow:

  ## default securityContext for Containers in airflow Pods
  ## - `runAsUser` is ignored, please set with per-image `*.image.uid`
  ## - `runAsGroup` is ignored, please set with per-image `*.image.gid`
  ## - spec for SecurityContext:
  ##   https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core
  ##
  defaultContainerSecurityContext:
    allowPrivilegeEscalation: false
```

Because not all images run with the same UID/GID, we can just ignore `runAsUser` and `runAsGroup` if they are passed using the [`omit` helm template function](https://helm.sh/docs/chart_template_guide/function_list/#omit), for example:

```yaml
securityContext:
  runAsUser: {{ .Values.airflow.image.uid }}
  runAsGroup: {{ .Values.airflow.image.gid }}
  {{- omit .Values.airflow.defaultContainerSecurityContext "runAsUser" "runAsGroup" | toYaml | nindent 2 }}
```

We will need to apply `airflow.defaultContainerSecurityContext` in more than just the airflow image, here is the full list:

- the `"airflow.image" ` template in `pods.tpl`
- the `"airflow.container.git_sync"` template in `pods.tpl`
- the PGBouncer container
- the embedded Redis will probably not be possible to set until we fix https://github.com/airflow-helm/charts/issues/304
- the embedded Postgres will probably not be possible to set until we fix https://github.com/airflow-helm/charts/issues/303
