### ISSUE TITLE
How to use a custom Docker image from a private Docker registry?

### ISSUE THREAD

**Issue by Felix-neko** [airflow-helm/charts#617]
Hi folks! And thank you for a great project.

In our company we have a private docker registry (artifactory) and need to use it to store our docker images.

So, if I want to use custom airflow docker image (par example, with some extra pip and apt packages installed) I should save this image in our private docker registry.

Can you please tell me, how can I tell `airflow`'s helm chart to pull image from private docker registry? And how to pass credentials in this case?

**Comment by karakanb** [comment]
The first thing you need to do is to create a image pull secret on Kubernetes, you can follow the tutorial [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).

Once you have the pull secret created in your cluster, you can simply pass it to the chart via `airflow.image.pullSecret` variable, here's an example:
```yaml
airflow:
    image:
        repository: registry.company.com/airflow/custom-image
        tag: latest # or any tag you'd like
        pullSecret: my-pull-secret
```

**Comment by LucaSoato** [comment]
Hi @karakanb, I've tried following your suggestion, but the only way to make it work was by using:
```yaml
images:
 airflow:
    repository: registry.company.com/airflow/custom-image
    tag: latest
```
Instead of:
```yaml
airflow:
  image:
    repository: registry.company.com/airflow/custom-image
    tag: latest
```
Is this expected? Did the helm config change recently?
