### ISSUE TITLE
variablesTemplates & connectionTemplates don't work

### ISSUE THREAD

**Issue by asosnovsky** [airflow-helm/charts#618]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

86.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

### Description

Specifying `variablesTemplates` or `connectionsTemplates` did not actually get picked up by the python code. Additionally, in order for these variables to be injected to the right pods you had to specify at least 1 variable or connection.

### Custom Helm Values

```yaml
airflow:
  airflow:
    legacyCommands: false
    image:
      repository: apache/airflow
      tag: 2.2.5-python3.9

    executor: KubernetesExecutor

    ###################################
    ## ENVIRONMENT VARIABLES SETUP
    ###################################
    config:
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      CONNECTION_CHECK_MAX_COUNT: 0
      AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws_airflow"
      AIRFLOW__LOGGING__LOGGING_LEVEL: "DEBUG"

    extraEnv:
      - name: AIRFLOW__WEBSERVER__BASE_URL
        valueFrom:
          configMapKeyRef:
            name: airflow-v2-settings
            key: webserver_url
      - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
        valueFrom:
          configMapKeyRef:
            name: airflow-v2-settings
            key: logging_bucket
      ## [SPEC] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/set-webserver-secret-key.md
      - name: AIRFLOW__WEBSERVER__SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: airflow-v2-external-secrets
            key: webKey

    ###################################
    ## AUTHENTICATION
    ###################################
    ## a list of users to create
    ## THIS WILL NEED TO BE DISABLED ONCE RBAC IS ENABLED
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/airflow-users.md
    users:
      - username: admin
        password: admin
        role: Admin
        email: admin@example.com
        firstName: admin
        lastName: admin

    variablesUpdate: true
    variablesTemplates:
      deployment:
        kind: configmap
        name: airflow-v2-settings
        key: deployment
    connectionsUpdate: true
    connectionsTemplates:
      slack:
        key: slack
        kind: secret
        name: airflow-v2-external-secrets

  ###################################
  ## REMOTE RESOURCES ACCESS
  ###################################
  externalDatabase:
    type: mysql
    host: "YOU FORGOT TO SET THIS" # this will need to be set in each value-<dep>.yaml file
    port: 3306
    database: airflow
    userSecret: airflow-v2-external-secrets
    userSecretKey: "db_username"
    passwordSecret: airflow-v2-external-secrets
    passwordSecretKey: "db_password"

  ###################################
  ## COMPONENTS
  ###################################
  ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
  resources:
    requests:
      memory: "1800Mi"
      cpu: "82m"
    values:
      memory: "1800Mi"
      cpu: "82m"

  scheduler:
    logCleanup:
      enabled: true
    securityContext:
      fsGroup: 65534
    replicas: 1
    resources:
      requests:
        memory: "1300Mi"
        cpu: "1600m"
      limits:
        memory: "1300Mi"
        cpu: "1600m"
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md
    livenessProbe:
      enabled: true
      ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md
      taskCreationCheck:
        enabled: false
        thresholdSeconds: 300

  web:
    securityContext:
      fsGroup: 65534
    replicas: 1
    resources:
      requests:
        memory: "3900Mi"
        cpu: "950m"
      limits:
        memory: "3900Mi"
        cpu: "950m"
    service:
      type: ClusterIP
      externalPort: 8080

  logs:
    path: /opt/airflow/logs
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md
    persistence:
      enabled: false

  dags:
    path: /opt/airflow/dags
    persistence:
      enabled: false

  ###################################
  ## Disabled Airflow Chart Services
  ###################################
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-cleanup.md
  logCleanup:
    enabled: false
  workers:
    enabled: false
  triggerer:
    enabled: false
  flower:
    enabled: false
  pgbouncer:
    enabled: false
  postgresql:
    enabled: false
  redis:
    enabled: false
  serviceAccount:
    create: false
  extraVolumeMounts: []
  extraVolumes: []
  ingress:
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/kubernetes/ingress.md
    enabled: false
```

**Comment by thesuperzapper** [comment]
@asosnovsky can you clarify what you mean by "does not work", as your custom values don't actually define any `airflow.connections` or `airflow.variables`?

The `airflow.connectionsTemplates` value works by defining the templates you need, and then you reference them in `airflow.connections`, for example:

```yaml
airflow: 
  connections:
    - id: my_aws
      type: aws
      description: my AWS connection
      
      ## this string template is defined by `airflow.connectionsTemplates.ACCESS_KEY_ID` 
      login: ${ACCESS_KEY_ID}
      
      ## this string template is defined by `airflow.connectionsTemplates.SECRET_ACCESS_KEY` 
      password: ${SECRET_ACCESS_KEY}
      
      ## see the official "aws" connection docs for valid extra configs
      extra: |
        {
          "region_name": "eu-central-1"
        }

  connectionsTemplates:
    ## extracts the value of AWS_ACCESS_KEY_ID from `Secret/my-aws-token`
    ACCESS_KEY_ID:
      kind: secret
      name: my-aws-token
      key: AWS_ACCESS_KEY_ID

    ## extracts the value of AWS_SECRET_ACCESS_KEY from `Secret/my-aws-token`
    SECRET_ACCESS_KEY:
      kind: secret
      name: my-aws-token
      key: AWS_SECRET_ACCESS_KEY
```

The full docs about [managing connections](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/dags/airflow-connections.md) give more examples and context.
