### ISSUE TITLE
airflow scheduler utilizing more CPU 

### ISSUE THREAD

**Issue by anu251989** [airflow-helm/charts#630]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-84b4fe6", GitCommit:"c813d094d1e9fa409079753049cfaa9a67524ed2", GitTreeState:"clean", BuildDate:"2022-06-09T18:20:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

### Description

The airflow scheduler utilizing more CPU after airflow2.2.5 upgrade and observed while parsing the dags every 30s or 300s.
We have updated MIN_FILE_PROCESS_INTERVAL to 300s. in our env, the dags are around 500 and while parsing the dags it is utilizing more than 2core cpu and utilization coming down to 800mi core.

AIRFLOW__SCHEDULER__FILE_PARSING_SORT_MODE: "modified_time"
AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "300"
AIRFLOW__SCHEDULER__PARSING_PROCESSES: "4" 

We have enabled HPA for scheduler and scaling another pod but that is also utilizing same CPU. The parsing of dags is not being shared by two schedulers. 

with one scheduler while parsing dags:
airflow-scheduler-65d69754bc-jv2sr      2225m        911Mi

with 3 schedulers while parsing dags:
airflow-scheduler-5cf7dff7d5-bwzz2       1796m        1059Mi
airflow-scheduler-5cf7dff7d5-gp24n       1988m        1103Mi
airflow-scheduler-5cf7dff7d5-nscxn       1768m        1090Mi

We would like to know why CPU utilization high while parsing dags every  300s. Can you please suggest the best configuration for scheduler with 1000 dags. 

Is it fine to enable the HPA for scheduler based on CPU utilization?

### Custom Helm Values

```yaml
we are not using custom values.yaml. all are default values except below mentioned.

AIRFLOW__SCHEDULER__FILE_PARSING_SORT_MODE: "modified_time"
AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "300"
AIRFLOW__SCHEDULER__PARSING_PROCESSES: "4"

scheduler:

  replicas: 1

  resources:
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: "3000m"
      memory: "12Gi"
```
