### ISSUE TITLE
Failed to init pods with mysql external DB

### ISSUE THREAD

**Issue by ykecheng** [airflow-helm/charts#639]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}
```

### Description

Hello,

I'm trying to build airflow with KubernetesExecutor on my cluster.
I'm using defult [sample-values-KubernetesExecutor.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/sample-values-KubernetesExecutor.yaml)

Also, I would to use my company's Mysql as externalDatabase.

I can use helm to install/upgrade, but I always got following error as Relevant Logs:

### Relevant Logs

```shell
Controlled By:  ReplicaSet/airflow-db-migrations-688974ffc7
Init Containers:
  check-db:
    Container ID:  docker://b6d782feead52a47ebe7ff5d23f40ef0a189f0c4700ca5b1a7d729257de95c37
    Image:         apache/airflow:2.2.5-python3.8
    Image ID:      docker-pullable://apache/airflow@sha256:d581907efc8ca601d72dcd41d6c1acef698e48abc2a96e4251ffcd7f50f1b098
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
      /entrypoint
    Args:
      bash
      -c
      exec timeout 60s airflow db check
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 26 Aug 2022 17:25:04 +0900
      Finished:     Fri, 26 Aug 2022 17:25:12 +0900
    Ready:          False
    Restart Count:  13
    Environment Variables from:
      airflow-config-envs  Secret  Optional: false
    Environment:
      CONNECTION_CHECK_MAX_COUNT:  0
    Mounts:
      /opt/airflow/logs from logs-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x4vvh (ro)
Containers:
  db-migrations:
    Container ID:  
    Image:         apache/airflow:2.2.5-python3.8
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
      /entrypoint
    Args:
      python
      -u
      /mnt/scripts/db_migrations.py
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      airflow-config-envs  Secret  Optional: false
    Environment:
      CONNECTION_CHECK_MAX_COUNT:  0
    Mounts:
      /mnt/scripts from scripts (ro)
      /opt/airflow/logs from logs-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x4vvh (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  logs-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  scripts:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  airflow-db-migrations
    Optional:    false
  kube-api-access-x4vvh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  45m                  default-scheduler  Successfully assigned airflow/airflow-db-migrations-688974ffc7-x9gnp to datamngs-default-5njnggr2nd-1
  Normal   Pulled     43m (x5 over 45m)    kubelet            Container image "apache/airflow:2.2.5-python3.8" already present on machine
  Normal   Created    43m (x5 over 45m)    kubelet            Created container check-db
  Normal   Started    43m (x5 over 45m)    kubelet            Started container check-db
  Warning  BackOff    42s (x202 over 45m)  kubelet            Back-off restarting failed container
```

### Custom Helm Values

```yaml
###################################
## DATABASE | PgBouncer
###################################
pgbouncer:
  ## if the pgbouncer Deployment is created
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/database/pgbouncer.md
  enabled: false

  ## resource requests/limits for the pgbouncer Pods
  ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
  resources: {}

  ## sets pgbouncer config: `auth_type`
  authType: md5

###################################
## DATABASE | Embedded Postgres
###################################
postgresql:
  ## if the `stable/postgresql` chart is used
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/database/embedded-database.md
  ## [WARNING] the embedded Postgres is NOT SUITABLE for production deployments of Airflow
  ## [WARNING] consider using an external database with `externalDatabase.*`
  enabled: false

  ## configs for the PVC of postgresql
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

###################################
## DATABASE | External Database
###################################
externalDatabase:
  ## the type of external database
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/database/external-database.md
  type: mysql
  
  host: airflow-dev.verda-datamngs.jp2-dev.db.line-apps-dev.com
  port: 20306

  ## the database which will contain the airflow tables
  database: airflow_db

  ## (username - option 1) a plain-text helm value
  user: airflow_user

  ## (username - option 2) a Kubernetes secret in your airflow namespace
  #userSecret: "airflow-cluster1-database-credentials"
  #userSecretKey: "username"

  ## (password - option 1) a plain-text helm value
  password: mypassword

  ## (password - option 2) a Kubernetes secret in your airflow namespace
  #passwordSecret: "airflow-cluster1-database-credentials"
  #passwordSecretKey: "password"

  ## use this for any extra connection-string settings, e.g. ?useSSL=false
  properties: ""
```
