### ISSUE TITLE
Question about `Only works with the Celery or Kubernetes executors, sorry`

### ISSUE THREAD

**Issue by sakaia** [airflow-helm/charts#64]
**What is the bug?**
I try to execute [tutorial.py](https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html) from web ui but failed with following error. 

```
Only works with the Celery or Kubernetes executors, sorry
```

From digging this error, it seems airflow 1.10.12 problem.

- [KubernetesExecutor single task run error: Only works with the Celery or Kubernetes executors, sorry #12341](https://github.com/apache/airflow/issues/12341)

If I execute on command line `airflow backfill`, it works fine.
Is there any workaround?

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`

```
###################################
# Airflow - Common Configs
###################################
airflow:
  ## the airflow executor type to use
  ##
  executor: "KubernetesExecutor"
  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.12"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"

workers:
  enabled: false # Celery workers

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs for the Service of the web Pods
  ##
  service:
    type: NodePort

###################################
# Airflow - Logs Configs
###################################
logs:
  persistence:
    enabled: true
    storageClass: basic-csi

###################################
# Airflow - DAGs Configs
###################################
dags:
  persistence:
    enabled: true
    storageClass: basic-csi
    accessMode: ReadWriteMany
    size: 1Gi
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
