### ISSUE TITLE
`PodDisruptionBudget` and `HorizontalPodAutoscaler` use unavailable apis (fix Kubernetes 1.25+)

### ISSUE THREAD

**Issue by fbertos** [airflow-helm/charts#679]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

Hi,

We would like to deploy Airflow v2.3.3 with Chart version 8.6.1 on Kubernetes 1.23.12 with the following worker configuration:

```yaml
  podDisruptionBudget:
    enabled: true
    minAvailable: "1"

  autoscaling:
    enabled: true
    maxReplicas: 16
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```

However it is not working correctly and we receive this warning:

```
W1212 17:03:04.202853    6021 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W1212 17:03:08.336673    6021 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
```

### Implementation

To change the templates of the worker:
- `worker-hpa.yaml`
- `worker-pdb.yaml`

To use the API version `policy/v1` and `autoscaling/v2` for these specs.

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [X] I can help test the feature!
