### ISSUE TITLE
airflow scheduler and worker memory leak

### ISSUE THREAD

**Issue by anu251989** [airflow-helm/charts#683]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

EKS1.21
```

### Helm Version

```shell
8.6.0
```

### Description

The scheduler and Worker pods memory keep on increasing day by day. The worker and scheduler pods scaled up max pods. 

![image](https://user-images.githubusercontent.com/106726701/210233513-0bfa3ae0-a538-4f4b-9882-ead13b1787b5.png)

![image](https://user-images.githubusercontent.com/106726701/210233599-3c9b872d-fda5-43ef-ae08-b69428334734.png)

### Custom Helm Values

```yaml
AIRFLOW__CORE__PARALLELISM: "120"
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "40"
    AIRFLOW__CELERY__WORKER_CONCURRENCY: "20"
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: "600"
```
