### ISSUE TITLE
Can't fetch DAGs from git using git-sync and ssh

### ISSUE THREAD

**Issue by MateuszWieczorek-TomTom** [airflow-helm/charts#689]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

1.7.0
https://airflow.apache.org/docs/helm-chart/1.7.0/manage-dags-files.html

### Ariflow Version

2.4.1

### Kubernetes Version

```shell
AKS 1.23.8
```

### Helm Version

```shell
GitHub Action

- name: Install helm
  uses: azure/setup-helm@v3
  with:
    version: 'v3.11.0'
```

### Description

I can't fetch git repository using SSH. I have generated new ssh rsa keys. 
Public key is deploy on Github. Private key I used in helm chart.

I have verified credentials using the following command:
`ssh-agent bash -c 'ssh-add airflow-dag-private-key-file; git clone git@github.com:repo-name.git'`

In k8s secrets `airflow-ssh-secret` is visible and the value is correct.

When we look at the logs, we can see `git-sync` is trying to load key from `/etc/git-secret/ssh` location.
I found the following [git-sync v3.4.0 docs](https://github.com/kubernetes/git-sync/blob/v3.4.0/docs/ssh.md) - there is `mountPath: /etc/git-secret`. I don't know if this is a good lead.

Is there anything else I missed?

### Relevant Logs

```shell
Run(git clone --no-checkout -b main --depth 1 git@github.com:repo-name.git /git): 
exit status 128: 
{ 
	stdout: "", 
	stderr: "Cloning into '/git'...
	Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
	Load key "/etc/git-secret/ssh": invalid format git@github.com: Permission denied (publickey).
	fatal: Could not read from remote repository.
	Please make sure you have the correct access rights and the repository exists."
}
```

### Custom Helm Values

```yaml
dags:
  gitSync:
    enabled: true
    repo: git@github.com:repo-name.git
    branch: main
    subPath: dags
    sshKeySecret: airflow-ssh-secret
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: 'my-base64-private-key-content'
```
