### ISSUE TITLE
Username in airflow.usersTemplates is not used by sync_users.py

### ISSUE THREAD

**Issue by robkuehl** [airflow-helm/charts#711]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.X.X

### Kubernetes Version

```shell
Client Version: v1.26.1
Server Version: v1.23.12
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

### Description

I used the helm chart to deploy Airflow into an Openshift cluster.
I used the docs https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/airflow-users.md to define an admin user.
Password and e-mail address are set as defined in the provided Kubernetes secret. The username was set to ${ADMIN_USERNAME} instead of the corresponding value in the secret.
From my point of view it is either a bug or it should be documented that the username can't be set by usersTemplates.

### Custom Helm Values

```yaml
users:
  ## define the user called "admin"
  - username: ${ADMIN_USERNAME}
    role: Admin
    firstName: Admin
    lastName: Admin
    email: ${ADMIN_EMAIL}
    ## use the ADMIN_PASSWORD template defined in `airflow.usersTemplates`
    password: ${ADMIN_PASSWORD}
  
## bash-like templates to be used in `airflow.users`
usersTemplates:
  ## define the `ADMIN_PASSWORD` template from the `my-secret` Secret
  ADMIN_PASSWORD:
    kind: secret
    name: airflow-admin-secret
    key: password
  
  ADMIN_EMAIL:
    kind: secret
    name: airflow-admin-secret
    key: email
  
  ADMIN_USERNAME:
    kind: secret
    name: airflow-admin-secret
    key: username
```
