### ISSUE TITLE
Operation not permitted: '/opt/airflow/logs/...'

### ISSUE THREAD

**Issue by obeyda** [airflow-helm/charts#712]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"08d3594304660f86cfbd17bbb862041b4b75fe6c", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:59Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

### Description

- persistence enabled
- used `airflow.defaultSecurityContext.fsGroup: 0` without setting any other `securityContext` 
- followed the "how to persist logs" doc

result: No problem in airflow pods but KubernetesExecutorPods can't write to the logs volume

### Relevant Logs

```shell
2023-04-05T02:46:39.148471134Z stderr F PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=xxx/run_id=manual__2023-04-05T02:46:26.041418+00:00/task_id=xxx_01'
```

### Custom Helm Values

```yaml
airflow:
  image:
    tag: 2.5.3-python3.10
  executor: "KubernetesExecutor"
  usersUpdate: false
  config:
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__WEBSERVER__COOKIE_SAMESITE: "Lax"
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  defaultSecurityContext:
    fsGroup: 0
  kubernetesPodTemplate:
    podLabels:
      my-label: "true"
logs:
  path: /opt/airflow/logs
  persistence:
    enabled: true
    storageClass: azurefile
    size: 128Gi
scheduler:
  logCleanup:
    enabled: false
workers:
  enabled: false
redis:
  enabled: false
flower:
  enabled: false
dags:
  gitSync:
    enabled: true
    repo: xxxx
    branch: main
    revision: HEAD
    depth: 1
    repoSubPath: ""
    httpSecret: airflow-git-credentials
```
