### ISSUE TITLE
using more than 1 web replica causes "CSRF session token is missing"

### ISSUE THREAD

**Issue by rg2609** [airflow-helm/charts#72]
I am trying to run airflow web with replica count 2 the helm chart gets installed and the login UI is shown up, but when I entered the login detail m getting an error `The CSRF session token is missing`. The Helm chart is working with web replica count 1. My main intention was to check the scalability of the web

**What are your Helm values?**

web.replicas=2

**following UI I am getting when I hit login button
![Screenshot from 2021-02-15 13-33-58](https://user-images.githubusercontent.com/20682661/107934524-2e7b0300-6fa6-11eb-82c7-695257c1b37e.png)

**Comment by karakanb** [comment]
I am having the same issue, the problem is gone once there is only a single replica for the web.

**Comment by thesuperzapper** [comment]
@rg2609 can you please try with version `8.0.0` of the chart and see if there is still an issue?

**Comment by tejasshekokar** [comment]
I am also facing the same issue. 
Chart Version: 8.0.7. 
+1

**Comment by cocampbe** [comment]
Same. Chart 8.0.9.

**Comment by cocampbe** [comment]
After digging into this a little, this seems to either be related a need to add a session "sticky" at the ingress controller or it is related to FAB. If I find a resolution I will post it here.

**Comment by cocampbe** [comment]
Well, that was simple. I use nginx for ingress. Adding this annotation to the ingress resolved the CSRF issue.

> nginx.ingress.kubernetes.io/affinity: cookie

**Comment by andormarkus** [comment]
Hi

We are using AWS EKS and `aws-load-balancer-controller` ingress controller.
Based on their [documentation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/) you can enable "sticky sessions". Once "sticky sessions" enabled it will work.
```yaml
ingress:
  enabled: true
  web:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60

```
