### ISSUE TITLE
[bug] default postgresql in helm chart (FATAL: password authentication failed for user "postgres")

### ISSUE THREAD

**Issue by seunggabi** [airflow-helm/charts#723]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```

### Description

FATAL: password authentication failed for user "postgres"

How can I fix?

### Relevant Logs

```shell
Liveness probe failed: psql: error: FATAL: password authentication failed for user "postgres" FATAL: password authentication failed for user "postgres"
```

### Custom Helm Values

```yaml
airflow:
  airflow:
    securityContext:
      fsGroup: 65534
    image:
      repository: apache/airflow
      tag: 2.4.3-python3.8
    executor: CeleryExecutor
    fernetKey: 7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc=
    webserverSecretKey: "THIS IS UNSAFE!"
    extraPipPackages:
      - awscli
      - apache-airflow
      - apache-airflow-providers-amazon==1.1.0
      - cached_property
    config:
      AIRFLOW__CORE__LOAD_EXAMPLES: false
      AIRFLOW__CORE__REMOTE_LOGGING: "True"
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://bucket/airflow/logs"
      AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "aws_default"
      AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://bucket/airflow/logs"
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws_default"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: false
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Seoul
      AIRFLOW__WEBSERVER__BASE_URL: https://airflow.com
  web:
    securityContext:
      fsGroup: 65534
    replicas: 1
    service:
      type: NodePort
  dags:
    gitSync:
      enabled: true
      repo: "git..."
      branch: main
      revision: HEAD
      syncWait: 60
  scheduler:
    securityContext:
      fsGroup: 65534
  workers:
    securityContext:
      fsGroup: 65534
```
