### ISSUE TITLE
Can't change Helm configuration for db-migrations job

### ISSUE THREAD

**Issue by aodj** [airflow-helm/charts#727]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.16", GitCommit:"b28e1f370a4a4c428ddbeababcaf0198f048fcac", GitTreeState:"clean", BuildDate:"2022-11-09T13:30:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-27T22:54:20Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}
```

### Description

It's not possible to change the `helm.sh` annotations on for the db-migrations job as they are [hardcoded](https://github.com/airflow-helm/charts/blob/f5c2f0cd617982c642789cf66fdef48453f84e67/charts/airflow/templates/db-migrations/db-migrations-job.yaml#L23-L25) in the template:

```yaml
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation
```

In the environment I'm deploying Airflow to, deployments are handled by Argo which waits for the webserver and scheduler to become "healthy" when deploying, before continuing with the db-migrations job, as defined by the `helm.sh/hook` value.

As the job is set to run `post-install`, Argo doesn't run it until the other resources are ready (as explained in the Helm documentation under [Hooks and the Release Lifecycle](https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle)). This means in a new install, the `check-for-db-migrations` initContainer will never complete, because the `db-migrations` job can't run, as the webserver and scheduler never become ready.

I thought it would be a simple case of setting the `annotations` in the `values.yaml` but I see now that the chart has them hard coded, and any attempt to set these `helm.sh` annotations results in invalid yaml:

```yaml
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
```

This also applies to the other jobs, but they aren't critical for starting the deployments, so will eventually resolve themselves.
