### ISSUE TITLE
How to use the HPA of worker

### ISSUE THREAD

**Issue by rg2609** [airflow-helm/charts#73]
**How to use the **HPA** of the worker, What is the config. to test it with simple example?**

I am trying to test the use of the HPA of the worker, to if the load is giving on the worker then how is a response with the pod. I set **2 replicas** of the worker `workers.replicas: 2` and enabled **autoscaling** 
```
autoscaling:
    enabled: true
    maxReplicas: 16
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```

**And created a simple dag file** 
```
from datetime import datetime
from airflow import DAG
from airflow.operators.dummy import DummyOperator
from airflow.operators.python import PythonOperator
from pprint import pprint
import pandas as pd


def gen_file():
    print('Hello world!')
    dicts = {"a": ["aaa", "aaaa", "aaaaa"], "b": ["bb", "bbb", "bbbb"]}
    df = pd.DataFrame.from_dict(dicts)
    df.to_csv("/opt/airflow/out_file11.csv", index=False)


dag = DAG(
    'hello_world',
    description='Simple tutorial DAG',
    schedule_interval='* * * * *',
    start_date=datetime(2017, 3, 20),
    catchup=False,
)

dummy_operator = DummyOperator(task_id='dummy_task', retries=3, dag=dag)

python_operator = PythonOperator(
    task_id='hello_task', python_callable=gen_file, dag=dag
)

dummy_operator >> python_operator
```
And I am triggering this dag from Api curl, I triggered this curl in a loop of 10000 from multiple terminals. The usage of the two pods of the worker is going huge but not increasing the count of the worker pod.
```
airflow-test-worker-0                                    2570m        1243Mi
airflow-test-worker-1                                    2163m        1338Mi
```
I just wanted to know that is my configuration is fine or if something is missing in my configuration in `values.yaml`. And what will the simplest configuration to test the HPA of the worker?
