### ISSUE TITLE
Remote logging to S3 bucket did not succeed

### ISSUE THREAD

**Issue by sunhongmin225** [airflow-helm/charts#734]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.7.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:23Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.8-eks-ec5523e", GitCommit:"83fe90de881ffe7450876d204ccdc37a0f95bda3", GitTreeState:"clean", BuildDate:"2023-03-20T21:32:06Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

### Description

I've decided to use S3 bucket among **Remote Providers** to **Manage Airflow Logs** as described in [this link](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md#option-2---remote-providers).

As described in below **Custom Helm Values** file, I have set necessary configurations such as `airflow.config`, `airflow.connections`, and `serviceAccount.annotations`. I've also confirmed that my IAM role linked to the Service Account has necessary permissions to write to the above-mentioned S3 bucket.

I've run `canary_dag` in the example in the bottom of [this link](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/scheduler-liveness-probe.md#scheduler-heartbeat-check), and it ran successfully.

I expect that the logs produced by this DAG are sent (remotely) to the S3 bucket that I've designated. However, when I go into my AWS account and check the bucket, nothing was written down.

What may be the problem? Or at least, where can I find necessary log messages related to the failure of sending the log remotely to the S3 bucket? I.e., among the pods that are deployed via User-Community Airflow Helm Chart, which pod (and which container) is responsible for this remote logging?

### Custom Helm Values

```yaml
airflow:
  config:
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://<REDACTED>/logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws-conn-id"
  connections:
    - id: aws-conn-id
      type: aws
      description: AWS connection used for remote log writing to a S3 bucket
      extra: |
        {
          "region_name": "ap-northeast-2"
        }

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<REDACTED>:role/<REDACTED>"
```
