### ISSUE TITLE
The airflow.connections parameter is not working as expected for Databricks connection

### ISSUE THREAD

**Issue by ViniciusNoggo** [airflow-helm/charts#736]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-27T22:54:20Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}
```

### Description

I'm trying to configure the connections using the` airflow.connections` parameter like the [documentation](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/dags/airflow-connections.md#manage-airflow-connections) points out.

Specifically for the Databricks connection I'm having a problem to authenticate when trying to use the token in the `password` field. 

I created a secret to store the connection token and used it in the `airflow.connectionsTemplates` to propagate to the `airflow.connections`.

Once I have the token in the `password` field and I test the connection in the UI the result that I receive is a 401 error (HTTP ERROR 401).

![4OLZc](https://user-images.githubusercontent.com/120049126/235561439-abf92da1-ec35-458c-ad3a-ac1618adc611.png)

The thing is, if I change the `values.yaml` file and start using the `extra` field instead the `password` or if I copy the exactly same token and paste it manually in the `password` field using directly the Airflow UI, in both cases the test succeeded.

The `extra` field mentioned above would be configured like this:

```
      extra: |
        {
          "token": "${JOB_DATABRICKS_TOKEN}"
        }
```

![62Eon](https://user-images.githubusercontent.com/120049126/235561456-bf9b4898-6296-4590-8b7b-afeb1a1fa067.png)

For security reasons and to avoid depending on manual post-install steps to configure the connection I want to use the parameters and not the UI. 

Any help towards that?

### Relevant Logs

```shell
HTTP ERROR 401
Problem accessing /api/2.0/clusters/spark-versions. 
Reason: Unauthorized
```

### Custom Helm Values

```yaml
airflow:
  connections:
    - id: conn_databricks_getd
      type: databricks
      host: ${DATABRICKS_HOST}
      password: ${DATABRICKS_TOKEN}
  connectionsTemplates:
    DATABRICKS_HOST:
      kind: secret
      name: secret-credentials-databricks
      key: DATABRICKS_HOST  
    DATABRICKS_TOKEN:
      kind: secret
      name: secret-credentials-databricks
      key: DATABRICKS_TOKEN
```
