### ISSUE TITLE
airflow.extraEnv not being setup as environment variable in worker pods under KubernetesExecutor 

### ISSUE THREAD

**Issue by vignesh-amido** [airflow-helm/charts#77]
**What is your question?**

I'm trying to setup some environment variables using extraEnv which I expect should get propagated to Worker pod. That doesn't seems to be the case, I can see all the values are properly set at scheduler pod, but when it spawns a worker values set under extraEnv doesn't seem to be there, is there anything I've done wrongly here? or is this a bug? 

Airflow: 1.10.14
Kubernetes: v1.18.8
Minikube: v1.17.1
Helm: v3.5.2

Following is my custom values file,

```
airflow:
  image:
    repository: airflow-global-local
    tag: 1.0.0
    pullPolicy: IfNotPresent

  executor: KubernetesExecutor

  fernetKey: "xxxxxx"

  config:
    # Security
    AIRFLOW__CORE__SECURE_MODE: "False"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__WEBSERVER__RBAC: "False"

    # DAGS
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    #K8s
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: "True"

    #remote logging to s3
    AIRFLOW__CORE__REMOTE_LOGGING: "True"
    AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://xxxx"
    AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "aws_logging"

    ## Disable noisy "Handling signal: ttou" Gunicorn log messages
    GUNICORN_CMD_ARGS: "--log-level WARNING"
    ENVIRONMENT: "dev"
    
  extraEnv:
    - name: VAULT_ROLE_ID
      valueFrom:
        secretKeyRef:
          name: airflow-core-secrets
          key: VAULT_ROLE_ID
    - name: VAULT_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: airflow-core-secrets
          key: VAULT_SECRET_ID    
    - name: TEAMS_WEBHOOK
      valueFrom:
        secretKeyRef:
          name: airflow-core-secrets
          key: TEAMS_WEBHOOK

externalDatabase:
  type: postgres
  host: xxxxx
  port: 5432
  database: airflow
  user: root
  passwordSecret: "airflow-core-secrets"
  passwordSecretKey: "DB_PASSWORD"

scheduler:
  connections:
    - id: aws_logging
      type: aws
      extra: |
        {
          "aws_access_key_id": "xxxxx",
          "aws_secret_access_key": "xxxxx",
          "region_name":"eu-west-1"
        }
  livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 5


postgresql:
  enabled: False

redis:
  enabled: False

flower:
  enabled: False

workers:
  enabled: False
```

Any help is much appreciated.
