### ISSUE TITLE
git synch error

### ISSUE THREAD

**Issue by bartolamey** [airflow-helm/charts#793]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.8.0

### Kubernetes Version

```shell
Client Version: v1.28.2
Server Version: v1.27.3
```


### Helm Version

```shell
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}
```


### Description

Good afternoon, I deployed the latest version of airflow. Enabled git-sync(sshSecret and httpSecret). The dougs appeared, everything works great. As soon as I make changes to the branch, under git-sync it gives an error exit status 128: { stdout: "", stderr: "fatal: git cat-file: could not get object info" }" "rev"="HEAD" "

### Relevant Logs

```shell
I1009 07:00:53.517282      10 main.go:1112] "level"=0 "msg"="update required" "rev"="HEAD" "local"="1a17c49fead598d020850c293823a0f46fe8332e" "remote"="499938761a71891bcc299e3e39ec08c530135e0d"                                                                                                                                                                                                                                                  ││ I1009 07:00:53.517326      10 main.go:760] "level"=0 "msg"="syncing git" "rev"="HEAD" "hash"="499938761a71891bcc299e3e39ec08c530135e0d"                                                                                                                                                                                                                                                                                                            ││ E1009 07:00:56.132600      10 main.go:781] "msg"="can't resolve commit, will retry" "error"="Run(git cat-file -t 499938761a71891bcc299e3e39ec08c530135e0d): exit status 128: { stdout: "", stderr: "fatal: git cat-file: could not get object info" }" "rev"="HEAD" "hash"="499938761a71891bcc299e3e39ec08c530135e0d"
```


### Custom Helm Values

```yaml
gitSync:
  enabled: true
  image:
    repository: registry.k8s.io/git-sync/git-sync
    tag: v3.6.5
    pullPolicy: IfNotPresent
    uid: 65533
    gid: 65533

  resources: {}

  repo: "git@github.com:***/***.git"

  repoSubPath: "dags"

  branch: dev

  revision: HEAD

  depth: 1

  syncWait: 60

  syncTimeout: 120

  submodules: recursive

  httpSecret: ""

  httpSecretUsernameKey: username

  httpSecretPasswordKey: password

  sshSecret: "airflow-ssh-git-secret"

  sshSecretKey: id_rsa

  sshKnownHosts: ""

  maxFailures: 0
```
