### ISSUE TITLE
Permission denied: '/opt/airflow/logs/scheduler'

### ISSUE THREAD

**Issue by cocampbe** [airflow-helm/charts#81]
**What is the bug?**

Using a PV to store logs. The storage is provided by longhorn. Since the PV is RWX longhorn presents the volume as an NFS mount using NFSv4. I am trying the volume mount hack, but it's failing. I think it is because NFSv4 usually defaults to everything being owned by nobody:nobody. I don't believe this is a code issue, just an implementation issue. I am hoping maybe someone has ran into issue with NFSv4 and con provide a workaround. 

I am going to submit a bug with longhorn also. 

**What are your Helm values?**

```console
   extraInitContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 logs"]
        volumeMounts:
          - mountPath: /opt/airflow/logs
            name: logs-data

  logs:
    persistance:
      enabled: true
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```

**Comment by cocampbe** [comment]
I figured it out. I was relying to much on the example to be valid. The airflow user uid/group is 50000. This ulitimately resolved the issue:

```yaml

extraInitContainers:
    - name: volume-mount-hack
      image: busybox
      command: ["sh", "-c", "chown -R 50000: /logs"]
      volumeMounts:
        - mountPath: /logs
          name: logs-data

```
