### ISSUE TITLE
Any ldap examples?

### ISSUE THREAD

**Issue by cocampbe** [airflow-helm/charts#82]
**What is your question?**

I am trying to setup ldap authentication in airflow. I have the following set in the helm chart. I should also add that I am trying to authenticate again AD. It's not listed below, but I have the ca cert in a config map that is also mounted. I verified that the airflow user can read the file.

```yaml 
 config:
    ## Security
    AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
    AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.ldap_auth"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__WEBSERVER__RBAC: "True"

    ## Email (SMTP)
    AIRFLOW__EMAIL__EMAIL_BACKEND: "airflow.utils.email.send_email_smtp"
    AIRFLOW__SMTP__SMTP_HOST: "smtp.example.com"
    AIRFLOW__SMTP__SMTP_STARTTLS: "False"
    AIRFLOW__SMTP__SMTP_SSL: "False"
    AIRFLOW__SMTP__SMTP_PORT: "25"
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"

    ## LDAP
    AIRFLOW__LDAP__URI: "ldaps://ldap.example.com:636"
    AIRFLOW__LDAP__USER_FILTER: "objectClass=*"
    AIRFLOW__LDAP__USER_NAME_ATTR: "sAMAccountName"
    AIRFLOW__LDAP__GROUP_MEMBER_ATTR: "memberOf"
    AIRFLOW__LDAP__GROUP_NAME_ATTR: "cn"
    AIRFLOW__LDAP__SUPERUSER_FILTER: "memberOf=cn=admins,ou=groups,dc=example,dc=com"
    #AIRFLOW__LDAP__DATA_PROFILER_FILTER: ""
    AIRFLOW__LDAP__BASEDN: "dc=example,dc=com"
    AIRFLOW__LDAP__SEARCH_SCOPE: "SUBTREE"
    AIRFLOW__LDAP__CACERT: "/etc/ca/ldap_ca.crt"
    AIRFLOW__LDAP__USE_TLS: "False"

      extraEnv:
    - name: AIRFLOW__LDAP__BIND_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-ldap-secret
          key: password
    - name: AIRFLOW__LDAP__BIND_USER
      valueFrom:
        secretKeyRef:
          name: airflow-ldap-secret
          key: bind_dn

```

The pods come up, and I am presented with a login. But I am unable to authenticate. I checked the logs of the pods, but there is nothing in the logs that provides a clue as to why auth is not working.
