### ISSUE TITLE
Logs persistence disabled not working

### ISSUE THREAD

**Issue by didlawowo** [airflow-helm/charts#832]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

1.11.0

### Kubernetes Version

```shell
using argocd
```

### Helm Version

```shell
using argocd
```

### Description

trying to disable logs persistence and set helm value to disable it

doesn't working

always provide a 100Gi pvc (which is huge...)

### Relevant Logs

```shell
│ mlops             logs-airflow-triggerer-0                    Bound   pvc-3794d1d9-7e48-4525-88c2-7e94362a9a10   100Gi     RWO           longhorn      11m
```

### Custom Helm Values

```yaml
helm:
      valuesObject:

        logs:
          persistence:
            enabled: false
            size: 10Gi
            existingClaim: airflow-logs


│
```
