### ISSUE TITLE
pods stuck in wait-for-airflow-migrations

### ISSUE THREAD

**Issue by espenthaem** [airflow-helm/charts#868]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [ ] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

1.13.1

### Kubernetes Version

```shell
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.13-eks-3af4770
WARNING: version difference between client (1.30) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}
```

### Description

I'm trying to deploy using Airflow but my scheduler, triggerer and webserver pods are forever stuck in wait-for-airflow-migrations to finish. However, a db-migrations job is never actually started. 

I'm using a customer docker image to include my package requirements:

```
# Use the official Apache Airflow image from Docker Hub
FROM apache/airflow:2.8.3
USER root
# Set environment variables
ENV AIRFLOW_HOME=/opt/airflow
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libsasl2-dev \
        gcc \
        build-essential \
        unzip \
        python3-dev \
        default-libmysqlclient-dev \
        libpq-dev \
        jq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements/requirements.txt .
ENV PIP_ENV_VERSION=24.0
RUN python -m pip install --no-cache-dir --upgrade pip==${PIP_ENV_VERSION}

COPY requirements/requirements.txt /tmp/tmp-pip/
RUN python -m pip install --no-cache-dir -r /tmp/tmp-pip/requirements.txt 
RUN pip list
ENTRYPOINT ["bash", "-c", "airflow db init && airflow webserver & airflow scheduler"]
```

### Relevant Logs

```shell
pod/airflow-postgresql-0                 1/1     Running    0              2m14s
pod/airflow-scheduler-79f69f58cf-75g6j   0/3     Init:0/2   0              2m14s
pod/airflow-statsd-7c56d8b68-5qntz       1/1     Running    0              2m14s
pod/airflow-triggerer-0                  0/3     Init:0/2   1 (119s ago)   2m14s
pod/airflow-webserver-6cdb66595f-pr7xc   0/1     Init:0/1   0              2m14s


Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m26s  default-scheduler  Successfully assigned airflow-dags/airflow-webserver-6cdb66595f-pr7xc to ip-10-30-196-195.eu-west-1.compute.internal
  Normal  Pulling    2m26s  kubelet            Pulling image "eu.gcr.io/medicuja/airflow-dags:ci_cd_helm_dependency-7"
  Normal  Pulled     116s   kubelet            Successfully pulled image "eu.gcr.io/my-project/airflow-dags:my-image-tag" in 30.190834116s (30.190864716s including waiting)
  Normal  Created    115s   kubelet            Created container wait-for-airflow-migrations
  Normal  Started    115s   kubelet            Started container wait-for-airflow-migrations
```

### Custom Helm Values

```yaml
images:
  airflow:
    repository: eu.gcr.io/my-project/airflow-dags
    tag: latest
airflow:
  dbMigrations:
    enabled: True
    runAsJob: True
dags:
  gitSync:
    branch: main
    enabled: true
    repo: 'git@github.com:my-repo/airflow-dags.git'
    subPath: 'dags'
    rev: HEAD
    sshKeySecret: airflow-git-key
  persistence:
    accessMode: ReadWriteOnce
    annotations: {}
    enabled: false
    existingClaim: null
    size: 1Gi
    storageClassName: null
    subPath: null
config:
  webserver:
    expose_config: 'True'
executor: KubernetesExecutor
extraEnv: |
    - name: "AIRFLOW__CORE__PLUGINS_FOLDER"
      value: "/opt/airflow/dags/repo/plugins"
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "True"
    - name: PYTHONPATH
      value: "/opt/airflow/dags/repo"
registry:
  secretName: my-project-gcr-secret-basic-service
```

I'm not using a `--wait` flag and I'm not deploying using ArgoCD. Here's my deploy statement:

```
helm upgrade airflow apache-airflow/airflow --namespace airflow-dags -f helm/values.yaml --set 'images.airflow.tag=image-tag' --atomic --install --timeout=5m
```
