### ISSUE TITLE
Add declarative custom roles 

### ISSUE THREAD

**Issue by ketozhang** [airflow-helm/charts#875]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

This chart can sync users, pools, connections, etc.

How about [custom roles](https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/access-control.html)?

Currently there are declarative alternatives (you cannot create a role from environment variable, only the UI, CLI and of course the Python package). https://github.com/apache/airflow/issues/38347

### Implementation

Would need another Helm template file that embeds a Python script (see https://github.com/airflow-helm/charts/tree/main/charts/airflow/templates/sync/_helpers). Eventually makes its way to the values. Perhaps something like

```yaml
airflow:
  users:
    - username: Alice
      role: [PythonTester]

  roles:
    - name: PythonTester
      permissions:
        - [can_read, dag]
```

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!
