### ISSUE TITLE
Dags changes from Azure blob fuse PVC not syncing in Airflow Schedular, triggerer, flower

### ISSUE THREAD

**Issue by kanika-bhargav** [airflow-helm/charts#898]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

2.10.2

### Kubernetes Version

```shell
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.15
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}
```

### Description

I have deployed azure blob fuse enabled PVC to load DAG definitions. I have a CI/CD pipeline to push the changes from git branch to azure blob container. We frequently make changes to DAG definition for testing and push to azure blob. The changes are reflected on az blob. But these changes are not syncing on airflow components except webserver. 

### Relevant Logs

```shell
Dont see anything in logs related to this
```

### Custom Helm Values

```yaml
airflow: 
   config:
      AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: '120.0'
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: '30'
      AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: '30'
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: '120'
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: '60'
      AIRFLOW__SCHEDULER__STALE_DAG_THRESHOLD: '90'
      AIRFLOW__SCHEDULER__ZOMBIE_DETECTION_INTERVAL: '60.0'
      AIRFLOW__SCHEDULER__PARSING_PROCESSES: '3'
      AIRFLOW__USAGE_DATA_COLLECTION__ENABLED: "False"
      AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS: 'content-type, origin, authorization, accept'
      AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS: 'GET, POST, PATCH, DELETE'
      AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS: "*"
      # auth backend (comma separated value for api auth. Default is session auth)
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.session, airflow.api.auth.backend.basic_auth


  ###################################
  ## CONFIG | Airflow DAGs
  ###################################
  dags:
    ## the airflow dags folder
    path: /opt/airflow/dags
    persistence:
      enabled: true
      existingClaim: "pvc-airflow-dags"
      accessMode: ReadWriteMany
```
