### ISSUE TITLE
Not adding the Connections via yaml/config

### ISSUE THREAD

**Issue by LozanoMatheus** [airflow-helm/charts#9]
**What is the bug?**
I'm trying to set up the connections via yaml/config, but it seems that's not getting it. I can see the environment variable in the container, but it doesn't add the connection.

I tried with `AIRFLOW_CONN_POSTGRES_DEFAULT`, `AIRFLOW__CONN_POSTGRES_DEFAULT` and `AIRFLOW__CONN__POSTGRES_DEFAULT`.

I got the example from here:
https://airflow.apache.org/docs/stable/howto/connection/postgres.html
https://airflow.apache.org/docs/stable/howto/connection/index.html

**Helm Chart Version?**

```bash
helm upgrade --install --version 7.14.0
```

**What are your Helm values?**

```yaml
airflow:
  config:
    AIRFLOW_CONN_POSTGRES_DEFAULT: 'postgresql://postgres_user:XXXXXXXXXXXX@1.1.1.1:5432/postgresdb?sslmode=verify-ca&sslcert=%2Ftmp%2Fclient-cert.pem&sslkey=%2Ftmp%2Fclient-key.pem&sslrootcert=%2Ftmp%2Fserver-ca.pem'
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
v1.17.9-eks-4c6976
```

**What is your Helm version?**:

```console
$ helm version
v3.4.0
```
