### ISSUE TITLE
Helm upgrade failed: execution error at (airflow/templates/sync/sync-users-secret.yaml:13:20): each password in airflow.users must be non-empty!

### ISSUE THREAD

**Issue by derangsx** [airflow-helm/charts#921]
### Checks

- [x] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [x] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.9.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.6-gke.1064001", ...}
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.6-gke.1064001", ...}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}
```

### Description

I am using usersTemplates to populate user passwords via an external secret. However, I encounter the following error during a Helm upgrade:

`Helm upgrade failed: execution error at (airflow/templates/sync/sync-users-secret.yaml:13:20): each `password` in `airflow.users` must be non-empty!`

This happens despite the fact that the secret is mounted correctly via ExternalSecrets and is present in the cluster.

This seems to be caused by how the chart handles user password values before the secrets are hydrated at runtime — causing Helm to treat ${ADMIN_PASSWORD} as empty or unset at templating time.

### Relevant Logs

```shell
Helm upgrade failed: execution error at (airflow/templates/sync/sync-users-secret.yaml:13:20): each `password` in `airflow.users` must be non-empty!
```

### Custom Helm Values

```yaml
airflow:
  executor: "KubernetesExecutor"
  config:
    AIRFLOW__WEBSERVER__BASE_URL: "http://airflow.example.com"
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "gs://airflow/airflow/logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "airflow_gcp"
    AIRFLOW__WEBSERVER__WARN_DEPLOYMENT_EXPOSURE: "false"

  users:
    - username: admin
      role: Admin
      firstName: admin
      lastName: admin
      password: ${ADMIN_PASSWORD}
      email: admin@example.com
  usersTemplates:
    ADMIN_PASSWORD:
      kind: secret
      name: airflow-users-secret
      key: password
  usersUpdate: true


airflow-users-secret is generated via an ExternalSecret:

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: airflow-users-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: env-secrets
  target:
    name: airflow-users-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: AIRFLOW_ADMIN_PASSWORD
```
