### ISSUE TITLE
Image tag overwrite has no impact

### ISSUE THREAD

**Issue by br41nlet** [airflow-helm/charts#925]
### Checks

- [x] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [x] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.9.0

### Kubernetes Version

```shell
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.31.5+k3s1
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.18.2", GitCommit:"04cad4610054e5d546aa5c5d9c1b1d5cf68ec1f8", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

### Description

It seems that image tag overwrite doesn't work, after I changed it to `2.10.5-python3.12`, it still deploys the one defined in the chart release (`airflow:2.8.4-python3.9`). I also tried `pullPolicy: Always` without success

### Relevant Logs

```shell
Image: apache/airflow:2.8.4-python3.9
Image ID: docker.io/apache/airflow@sha256:64e58748b6b970400d097d9e8a47dd4a3470cfe3c210edde466a15cfd22a70c0
```

### Custom Helm Values

```yaml
airflow:
  image:
      repository: apache/airflow
      tag: 2.10.5-python3.12
      pullPolicy: IfNotPresent
      pullSecret: ""
      uid: 50000
      gid: 0
```
